[{"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1913", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1913/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1913/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1913/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1913", "id": 1578105931, "node_id": "PR_kwDOAkVMUs5JoTgL", "number": 1913, "title": "Fix #1912", "user": {"login": "coder2020official", "id": 63740404, "node_id": "MDQ6VXNlcjYzNzQwNDA0", "avatar_url": "https://avatars.githubusercontent.com/u/63740404?v=4", "gravatar_id": "", "url": "https://api.github.com/users/coder2020official", "html_url": "https://github.com/coder2020official", "followers_url": "https://api.github.com/users/coder2020official/followers", "following_url": "https://api.github.com/users/coder2020official/following{/other_user}", "gists_url": "https://api.github.com/users/coder2020official/gists{/gist_id}", "starred_url": "https://api.github.com/users/coder2020official/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/coder2020official/subscriptions", "organizations_url": "https://api.github.com/users/coder2020official/orgs", "repos_url": "https://api.github.com/users/coder2020official/repos", "events_url": "https://api.github.com/users/coder2020official/events{/privacy}", "received_events_url": "https://api.github.com/users/coder2020official/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}, {"id": 4419280578, "node_id": "LA_kwDOAkVMUs8AAAABB2jewg", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/confirmed", "name": "confirmed", "color": "1C7D1F", "default": false, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2023-02-09T15:27:41Z", "updated_at": "2023-02-09T15:49:39Z", "closed_at": "2023-02-09T15:49:18Z", "author_association": "COLLABORATOR", "active_lock_reason": null, "draft": false, "pull_request": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/pulls/1913", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1913", "diff_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1913.diff", "patch_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1913.patch", "merged_at": "2023-02-09T15:49:17Z"}, "body": "Not yet done, just a draft", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1913/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1913/timeline", "performed_via_github_app": null, "state_reason": null}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1912", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1912/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1912/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1912/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/issues/1912", "id": 1578056702, "node_id": "I_kwDOAkVMUs5eDzv-", "number": 1912, "title": "async download_file issue", "user": {"login": "Badiboy", "id": 5613421, "node_id": "MDQ6VXNlcjU2MTM0MjE=", "avatar_url": "https://avatars.githubusercontent.com/u/5613421?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Badiboy", "html_url": "https://github.com/Badiboy", "followers_url": "https://api.github.com/users/Badiboy/followers", "following_url": "https://api.github.com/users/Badiboy/following{/other_user}", "gists_url": "https://api.github.com/users/Badiboy/gists{/gist_id}", "starred_url": "https://api.github.com/users/Badiboy/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Badiboy/subscriptions", "organizations_url": "https://api.github.com/users/Badiboy/orgs", "repos_url": "https://api.github.com/users/Badiboy/repos", "events_url": "https://api.github.com/users/Badiboy/events{/privacy}", "received_events_url": "https://api.github.com/users/Badiboy/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}, {"id": 4419280578, "node_id": "LA_kwDOAkVMUs8AAAABB2jewg", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/confirmed", "name": "confirmed", "color": "1C7D1F", "default": false, "description": ""}], "state": "closed", "locked": false, "assignee": {"login": "coder2020official", "id": 63740404, "node_id": "MDQ6VXNlcjYzNzQwNDA0", "avatar_url": "https://avatars.githubusercontent.com/u/63740404?v=4", "gravatar_id": "", "url": "https://api.github.com/users/coder2020official", "html_url": "https://github.com/coder2020official", "followers_url": "https://api.github.com/users/coder2020official/followers", "following_url": "https://api.github.com/users/coder2020official/following{/other_user}", "gists_url": "https://api.github.com/users/coder2020official/gists{/gist_id}", "starred_url": "https://api.github.com/users/coder2020official/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/coder2020official/subscriptions", "organizations_url": "https://api.github.com/users/coder2020official/orgs", "repos_url": "https://api.github.com/users/coder2020official/repos", "events_url": "https://api.github.com/users/coder2020official/events{/privacy}", "received_events_url": "https://api.github.com/users/coder2020official/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "coder2020official", "id": 63740404, "node_id": "MDQ6VXNlcjYzNzQwNDA0", "avatar_url": "https://avatars.githubusercontent.com/u/63740404?v=4", "gravatar_id": "", "url": "https://api.github.com/users/coder2020official", "html_url": "https://github.com/coder2020official", "followers_url": "https://api.github.com/users/coder2020official/followers", "following_url": "https://api.github.com/users/coder2020official/following{/other_user}", "gists_url": "https://api.github.com/users/coder2020official/gists{/gist_id}", "starred_url": "https://api.github.com/users/coder2020official/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/coder2020official/subscriptions", "organizations_url": "https://api.github.com/users/coder2020official/orgs", "repos_url": "https://api.github.com/users/coder2020official/repos", "events_url": "https://api.github.com/users/coder2020official/events{/privacy}", "received_events_url": "https://api.github.com/users/coder2020official/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 2, "created_at": "2023-02-09T15:01:19Z", "updated_at": "2023-02-09T15:49:19Z", "closed_at": "2023-02-09T15:49:19Z", "author_association": "COLLABORATOR", "active_lock_reason": null, "body": "Issue in \r\n`async download_file`\r\n\r\n![image](https://user-images.githubusercontent.com/5613421/217848942-1ff6b432-2c69-4c78-b931-a00af3a05b58.png)\r\n\r\n_result_ is used before assignment. I'm not sure how it should be, please, take a look.", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1912/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1912/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1910", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1910/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1910/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1910/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/issues/1910", "id": 1577980029, "node_id": "I_kwDOAkVMUs5eDhB9", "number": 1910, "title": "TypeError: 'ChatPermissions' object does not support item assignment", "user": {"login": "xvitaly", "id": 966711, "node_id": "MDQ6VXNlcjk2NjcxMQ==", "avatar_url": "https://avatars.githubusercontent.com/u/966711?v=4", "gravatar_id": "", "url": "https://api.github.com/users/xvitaly", "html_url": "https://github.com/xvitaly", "followers_url": "https://api.github.com/users/xvitaly/followers", "following_url": "https://api.github.com/users/xvitaly/following{/other_user}", "gists_url": "https://api.github.com/users/xvitaly/gists{/gist_id}", "starred_url": "https://api.github.com/users/xvitaly/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/xvitaly/subscriptions", "organizations_url": "https://api.github.com/users/xvitaly/orgs", "repos_url": "https://api.github.com/users/xvitaly/repos", "events_url": "https://api.github.com/users/xvitaly/events{/privacy}", "received_events_url": "https://api.github.com/users/xvitaly/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}, {"id": 4419280578, "node_id": "LA_kwDOAkVMUs8AAAABB2jewg", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/confirmed", "name": "confirmed", "color": "1C7D1F", "default": false, "description": ""}, {"id": 5135827723, "node_id": "LA_kwDOAkVMUs8AAAABMh6DCw", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/fixed", "name": "fixed", "color": "9607C7", "default": false, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 16, "created_at": "2023-02-09T14:20:02Z", "updated_at": "2023-02-09T15:21:57Z", "closed_at": "2023-02-09T14:59:21Z", "author_association": "NONE", "active_lock_reason": null, "body": "pyTelegramBotAPI version: 4.10.0\r\nOS: Microsoft Windows and Fedora Linux.\r\nPython version: 3.10.10\r\n\r\nSteps to reproduce:\r\n\r\n```python\r\nself._perm = telebot.types.ChatPermissions(can_send_messages=True, can_send_media_messages=False, can_send_audios=False, can_send_documents=False, can_send_photos=False, can_send_videos=False, can_send_video_notes=False, can_send_voice_notes=False, can_send_polls=False, can_send_other_messages=False, can_add_web_page_previews=False, can_change_info=False, can_invite_users=False, can_pin_messages=False, can_manage_topics=False)\r\n\r\n@property\r\ndef join(self):\r\n    return self._perm\r\n\r\nself._bot.restrict_chat_member(message.chat.id, userid, until_date=mutetime, permissions=self.join, use_independent_chat_permissions=True)\r\n```\r\n\r\nError:\r\n```\r\nTraceback (most recent call last):\r\n  File \"ecasbot\\__init__.py\", line 762, in __handle_join\r\n  File \"telebot\\__init__.py\", line 3001, in restrict_chat_member\r\n  File \"telebot\\apihelper.py\", line 977, in restrict_chat_member\r\nTypeError: 'ChatPermissions' object does not support item assignment\r\n```", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1910/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1910/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1888", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1888/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1888/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1888/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/issues/1888", "id": 1549400804, "node_id": "I_kwDOAkVMUs5cWfrk", "number": 1888, "title": "Ignore middleware", "user": {"login": "Blissbill", "id": 49755497, "node_id": "MDQ6VXNlcjQ5NzU1NDk3", "avatar_url": "https://avatars.githubusercontent.com/u/49755497?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Blissbill", "html_url": "https://github.com/Blissbill", "followers_url": "https://api.github.com/users/Blissbill/followers", "following_url": "https://api.github.com/users/Blissbill/following{/other_user}", "gists_url": "https://api.github.com/users/Blissbill/gists{/gist_id}", "starred_url": "https://api.github.com/users/Blissbill/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Blissbill/subscriptions", "organizations_url": "https://api.github.com/users/Blissbill/orgs", "repos_url": "https://api.github.com/users/Blissbill/repos", "events_url": "https://api.github.com/users/Blissbill/events{/privacy}", "received_events_url": "https://api.github.com/users/Blissbill/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2023-01-19T15:32:15Z", "updated_at": "2023-02-04T15:47:22Z", "closed_at": "2023-02-04T15:47:22Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hey\r\nI noticed that when using `register_next_step_handler`, the next call will ignore middleware. Is this done on purpose?\r\nIf so, is there a way to get around this limitation?\r\n\r\nPlease answer these questions before submitting your issue. Thanks!\r\n\r\n1. What version of pyTelegramBotAPI are you using?\r\npytelegrambotapi==4.9.0\r\n\r\n2. What OS are you using?\r\nWindows 11\r\n\r\n3. What version of python are you using?\r\nPython 3.9.10\r\n\r\n", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1888/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1888/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1872", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1872/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1872/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1872/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/issues/1872", "id": 1524204556, "node_id": "I_kwDOAkVMUs5a2YQM", "number": 1872, "title": "Circular imports ", "user": {"login": "Tishka17", "id": 6381317, "node_id": "MDQ6VXNlcjYzODEzMTc=", "avatar_url": "https://avatars.githubusercontent.com/u/6381317?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Tishka17", "html_url": "https://github.com/Tishka17", "followers_url": "https://api.github.com/users/Tishka17/followers", "following_url": "https://api.github.com/users/Tishka17/following{/other_user}", "gists_url": "https://api.github.com/users/Tishka17/gists{/gist_id}", "starred_url": "https://api.github.com/users/Tishka17/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Tishka17/subscriptions", "organizations_url": "https://api.github.com/users/Tishka17/orgs", "repos_url": "https://api.github.com/users/Tishka17/repos", "events_url": "https://api.github.com/users/Tishka17/events{/privacy}", "received_events_url": "https://api.github.com/users/Tishka17/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}, {"id": 229170312, "node_id": "MDU6TGFiZWwyMjkxNzAzMTI=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/duplicate", "name": "duplicate", "color": "cccccc", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2023-01-07T22:55:52Z", "updated_at": "2023-01-08T06:53:39Z", "closed_at": "2023-01-07T23:05:00Z", "author_association": "NONE", "active_lock_reason": null, "body": "Actually code is broken. No ideas how library can be imported in any cases.\r\n\r\nSome guys reported circular import error from python interpreter, so I've checked the source code and confirm, that there is a problem.\r\n\r\n![IMG_20230108_025331_952](https://user-images.githubusercontent.com/6381317/211173236-3fb7533a-efad-4364-916e-08ab07176c9a.jpg)\r\n", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1872/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1872/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1869", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1869/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1869/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1869/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/issues/1869", "id": 1523131110, "node_id": "I_kwDOAkVMUs5aySLm", "number": 1869, "title": "StatePickleStorage create_dir() fails with windows-like paths", "user": {"login": "Cub11k", "id": 22455000, "node_id": "MDQ6VXNlcjIyNDU1MDAw", "avatar_url": "https://avatars.githubusercontent.com/u/22455000?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Cub11k", "html_url": "https://github.com/Cub11k", "followers_url": "https://api.github.com/users/Cub11k/followers", "following_url": "https://api.github.com/users/Cub11k/following{/other_user}", "gists_url": "https://api.github.com/users/Cub11k/gists{/gist_id}", "starred_url": "https://api.github.com/users/Cub11k/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Cub11k/subscriptions", "organizations_url": "https://api.github.com/users/Cub11k/orgs", "repos_url": "https://api.github.com/users/Cub11k/repos", "events_url": "https://api.github.com/users/Cub11k/events{/privacy}", "received_events_url": "https://api.github.com/users/Cub11k/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}, {"id": 4419280578, "node_id": "LA_kwDOAkVMUs8AAAABB2jewg", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/confirmed", "name": "confirmed", "color": "1C7D1F", "default": false, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2023-01-06T20:35:46Z", "updated_at": "2023-01-08T06:54:53Z", "closed_at": "2023-01-07T11:54:42Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Please answer these questions before submitting your issue. Thanks!\r\n\r\n1. What version of pyTelegramBotAPI are you using?\r\n4.9.0\r\n\r\n2. What OS are you using?\r\nWindows\r\n\r\n3. What version of python are you using?\r\n3.10\r\n\r\nWindows-like paths are not splitted correctly and thus create_dir() fails when file already exists.", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1869/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1869/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1865", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1865/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1865/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1865/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1865", "id": 1519042562, "node_id": "PR_kwDOAkVMUs5GoSVZ", "number": 1865, "title": "Fix docs issues", "user": {"login": "coder2020official", "id": 63740404, "node_id": "MDQ6VXNlcjYzNzQwNDA0", "avatar_url": "https://avatars.githubusercontent.com/u/63740404?v=4", "gravatar_id": "", "url": "https://api.github.com/users/coder2020official", "html_url": "https://github.com/coder2020official", "followers_url": "https://api.github.com/users/coder2020official/followers", "following_url": "https://api.github.com/users/coder2020official/following{/other_user}", "gists_url": "https://api.github.com/users/coder2020official/gists{/gist_id}", "starred_url": "https://api.github.com/users/coder2020official/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/coder2020official/subscriptions", "organizations_url": "https://api.github.com/users/coder2020official/orgs", "repos_url": "https://api.github.com/users/coder2020official/repos", "events_url": "https://api.github.com/users/coder2020official/events{/privacy}", "received_events_url": "https://api.github.com/users/coder2020official/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2023-01-04T14:08:29Z", "updated_at": "2023-01-04T14:08:35Z", "closed_at": "2023-01-04T14:08:35Z", "author_association": "COLLABORATOR", "active_lock_reason": null, "draft": false, "pull_request": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/pulls/1865", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1865", "diff_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1865.diff", "patch_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1865.patch", "merged_at": "2023-01-04T14:08:35Z"}, "body": null, "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1865/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1865/timeline", "performed_via_github_app": null, "state_reason": null}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1864", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1864/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1864/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1864/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/issues/1864", "id": 1518993801, "node_id": "I_kwDOAkVMUs5aigGJ", "number": 1864, "title": "Circular import in types & util files", "user": {"login": "coder2020official", "id": 63740404, "node_id": "MDQ6VXNlcjYzNzQwNDA0", "avatar_url": "https://avatars.githubusercontent.com/u/63740404?v=4", "gravatar_id": "", "url": "https://api.github.com/users/coder2020official", "html_url": "https://github.com/coder2020official", "followers_url": "https://api.github.com/users/coder2020official/followers", "following_url": "https://api.github.com/users/coder2020official/following{/other_user}", "gists_url": "https://api.github.com/users/coder2020official/gists{/gist_id}", "starred_url": "https://api.github.com/users/coder2020official/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/coder2020official/subscriptions", "organizations_url": "https://api.github.com/users/coder2020official/orgs", "repos_url": "https://api.github.com/users/coder2020official/repos", "events_url": "https://api.github.com/users/coder2020official/events{/privacy}", "received_events_url": "https://api.github.com/users/coder2020official/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}, {"id": 4419280578, "node_id": "LA_kwDOAkVMUs8AAAABB2jewg", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/confirmed", "name": "confirmed", "color": "1C7D1F", "default": false, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2023-01-04T13:36:05Z", "updated_at": "2023-01-08T06:54:42Z", "closed_at": "2023-01-06T19:52:51Z", "author_association": "COLLABORATOR", "active_lock_reason": null, "body": "Types file imports util:\r\nhttps://github.com/eternnoir/pyTelegramBotAPI/blob/master/telebot/types.py#L15\r\nAnd util imports types:\r\nhttps://github.com/eternnoir/pyTelegramBotAPI/blob/master/telebot/util.py#L16\r\n\r\n@Badiboy any ideas on properly fixing the issue?\r\n\r\n", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1864/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1864/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1844", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1844/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1844/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1844/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1844", "id": 1505156848, "node_id": "PR_kwDOAkVMUs5F5dyM", "number": 1844, "title": "Fix #1843", "user": {"login": "coder2020official", "id": 63740404, "node_id": "MDQ6VXNlcjYzNzQwNDA0", "avatar_url": "https://avatars.githubusercontent.com/u/63740404?v=4", "gravatar_id": "", "url": "https://api.github.com/users/coder2020official", "html_url": "https://github.com/coder2020official", "followers_url": "https://api.github.com/users/coder2020official/followers", "following_url": "https://api.github.com/users/coder2020official/following{/other_user}", "gists_url": "https://api.github.com/users/coder2020official/gists{/gist_id}", "starred_url": "https://api.github.com/users/coder2020official/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/coder2020official/subscriptions", "organizations_url": "https://api.github.com/users/coder2020official/orgs", "repos_url": "https://api.github.com/users/coder2020official/repos", "events_url": "https://api.github.com/users/coder2020official/events{/privacy}", "received_events_url": "https://api.github.com/users/coder2020official/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}, {"id": 4419280578, "node_id": "LA_kwDOAkVMUs8AAAABB2jewg", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/confirmed", "name": "confirmed", "color": "1C7D1F", "default": false, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2022-12-20T19:47:51Z", "updated_at": "2022-12-21T12:59:03Z", "closed_at": "2022-12-21T12:59:03Z", "author_association": "COLLABORATOR", "active_lock_reason": null, "draft": false, "pull_request": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/pulls/1844", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1844", "diff_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1844.diff", "patch_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1844.patch", "merged_at": "2022-12-21T12:59:03Z"}, "body": "#1843 ", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1844/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1844/timeline", "performed_via_github_app": null, "state_reason": null}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1843", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1843/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1843/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1843/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/issues/1843", "id": 1505104854, "node_id": "I_kwDOAkVMUs5ZthPW", "number": 1843, "title": "Incorrect behaviour of escape_markdown", "user": {"login": "AsMaNick", "id": 23367296, "node_id": "MDQ6VXNlcjIzMzY3Mjk2", "avatar_url": "https://avatars.githubusercontent.com/u/23367296?v=4", "gravatar_id": "", "url": "https://api.github.com/users/AsMaNick", "html_url": "https://github.com/AsMaNick", "followers_url": "https://api.github.com/users/AsMaNick/followers", "following_url": "https://api.github.com/users/AsMaNick/following{/other_user}", "gists_url": "https://api.github.com/users/AsMaNick/gists{/gist_id}", "starred_url": "https://api.github.com/users/AsMaNick/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/AsMaNick/subscriptions", "organizations_url": "https://api.github.com/users/AsMaNick/orgs", "repos_url": "https://api.github.com/users/AsMaNick/repos", "events_url": "https://api.github.com/users/AsMaNick/events{/privacy}", "received_events_url": "https://api.github.com/users/AsMaNick/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}, {"id": 4419280578, "node_id": "LA_kwDOAkVMUs8AAAABB2jewg", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/confirmed", "name": "confirmed", "color": "1C7D1F", "default": false, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2022-12-20T18:58:58Z", "updated_at": "2022-12-20T20:03:36Z", "closed_at": "2022-12-20T20:03:36Z", "author_association": "NONE", "active_lock_reason": null, "body": "Please answer these questions before submitting your issue. Thanks!\r\n\r\n1. What version of pyTelegramBotAPI are you using?\r\n4.8.0\r\n2. What OS are you using?\r\nBoth Linux/Windows 10\r\n3. What version of python are you using?\r\nPython 3.9.0\r\n\r\nFunction `escape_markdown` from `telebot.formatting` doesn't escape symbols `{` and `}`, however according to the [core.telegram](https://core.telegram.org/bots/api#markdownv2-style) they must be escaped with the preceding character `\\`.\r\n\r\nIt means that now sending messages using `parse_mode='MarkdownV2'` gives the following error when the message text contains symbols `{` and `}`: `A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: can't parse entities: Character '{' is reserved and must be escaped with the preceding '\\'`.", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1843/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1843/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1840", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1840/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1840/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1840/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/issues/1840", "id": 1503907386, "node_id": "I_kwDOAkVMUs5Zo846", "number": 1840, "title": "enable_save_next_step_handlers(delay=2) \u62a5\u9519 TypeError: cannot pickle '_thread.lock' object", "user": {"login": "stonegr", "id": 74632994, "node_id": "MDQ6VXNlcjc0NjMyOTk0", "avatar_url": "https://avatars.githubusercontent.com/u/74632994?v=4", "gravatar_id": "", "url": "https://api.github.com/users/stonegr", "html_url": "https://github.com/stonegr", "followers_url": "https://api.github.com/users/stonegr/followers", "following_url": "https://api.github.com/users/stonegr/following{/other_user}", "gists_url": "https://api.github.com/users/stonegr/gists{/gist_id}", "starred_url": "https://api.github.com/users/stonegr/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/stonegr/subscriptions", "organizations_url": "https://api.github.com/users/stonegr/orgs", "repos_url": "https://api.github.com/users/stonegr/repos", "events_url": "https://api.github.com/users/stonegr/events{/privacy}", "received_events_url": "https://api.github.com/users/stonegr/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2022-12-20T02:55:02Z", "updated_at": "2023-01-04T14:14:38Z", "closed_at": "2023-01-04T14:14:38Z", "author_association": "NONE", "active_lock_reason": null, "body": "Please answer these questions before submitting your issue. Thanks!\r\n\r\n1. What version of pyTelegramBotAPI are you using?\r\n4.8.0\r\n2. What OS are you using?\r\nwindows\r\n3. What version of python are you using?\r\n3.10.5\r\n\r\n\u6253\u5f00\r\nbot.enable_save_next_step_handlers(delay=2)\r\nbot.load_next_step_handlers()\r\n\u8fd9\u4e24\u9879\u4e4b\u540e\uff0c\u62a5\u8fd9\u4e2a\u9519\r\n\r\n![\u622a\u56fe_20221220105249](https://user-images.githubusercontent.com/74632994/208570734-c8a751ac-a4a6-4c33-bd5c-88aff71f8648.png)\r\n\r\n\u611f\u8c22\u5f00\u53d1\u8005\u7684\u8f9b\u52e4\u5f00\u53d1", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1840/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1840/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1839", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1839/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1839/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1839/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1839", "id": 1502932390, "node_id": "PR_kwDOAkVMUs5FyDD6", "number": 1839, "title": "Fix bug with asyncwebhooks", "user": {"login": "coder2020official", "id": 63740404, "node_id": "MDQ6VXNlcjYzNzQwNDA0", "avatar_url": "https://avatars.githubusercontent.com/u/63740404?v=4", "gravatar_id": "", "url": "https://api.github.com/users/coder2020official", "html_url": "https://github.com/coder2020official", "followers_url": "https://api.github.com/users/coder2020official/followers", "following_url": "https://api.github.com/users/coder2020official/following{/other_user}", "gists_url": "https://api.github.com/users/coder2020official/gists{/gist_id}", "starred_url": "https://api.github.com/users/coder2020official/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/coder2020official/subscriptions", "organizations_url": "https://api.github.com/users/coder2020official/orgs", "repos_url": "https://api.github.com/users/coder2020official/repos", "events_url": "https://api.github.com/users/coder2020official/events{/privacy}", "received_events_url": "https://api.github.com/users/coder2020official/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2022-12-19T13:13:02Z", "updated_at": "2022-12-19T13:35:23Z", "closed_at": "2022-12-19T13:35:23Z", "author_association": "COLLABORATOR", "active_lock_reason": null, "draft": false, "pull_request": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/pulls/1839", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1839", "diff_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1839.diff", "patch_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1839.patch", "merged_at": "2022-12-19T13:35:23Z"}, "body": null, "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1839/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1839/timeline", "performed_via_github_app": null, "state_reason": null}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1832", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1832/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1832/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1832/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1832", "id": 1496074464, "node_id": "PR_kwDOAkVMUs5Fa1Wz", "number": 1832, "title": "Fix bug related to get_user_profile_photos", "user": {"login": "coder2020official", "id": 63740404, "node_id": "MDQ6VXNlcjYzNzQwNDA0", "avatar_url": "https://avatars.githubusercontent.com/u/63740404?v=4", "gravatar_id": "", "url": "https://api.github.com/users/coder2020official", "html_url": "https://github.com/coder2020official", "followers_url": "https://api.github.com/users/coder2020official/followers", "following_url": "https://api.github.com/users/coder2020official/following{/other_user}", "gists_url": "https://api.github.com/users/coder2020official/gists{/gist_id}", "starred_url": "https://api.github.com/users/coder2020official/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/coder2020official/subscriptions", "organizations_url": "https://api.github.com/users/coder2020official/orgs", "repos_url": "https://api.github.com/users/coder2020official/repos", "events_url": "https://api.github.com/users/coder2020official/events{/privacy}", "received_events_url": "https://api.github.com/users/coder2020official/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2022-12-14T08:42:03Z", "updated_at": "2022-12-14T10:18:19Z", "closed_at": "2022-12-14T10:18:19Z", "author_association": "COLLABORATOR", "active_lock_reason": null, "draft": false, "pull_request": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/pulls/1832", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1832", "diff_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1832.diff", "patch_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1832.patch", "merged_at": "2022-12-14T10:18:19Z"}, "body": "## Description\r\nInclude changes, new features and etc:\r\n\r\n## Describe your tests\r\nHow did you test your change?\r\n\r\nPython version:\r\n\r\nOS:\r\n\r\n## Checklist:\r\n- [ ] I added/edited example on new feature/change (if exists)\r\n- [ ] My changes won't break backward compatibility\r\n- [ ] I made changes both for sync and async\r\n", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1832/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1832/timeline", "performed_via_github_app": null, "state_reason": null}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1831", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1831/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1831/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1831/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1831", "id": 1494400187, "node_id": "PR_kwDOAkVMUs5FU_rB", "number": 1831, "title": "Update reloader.py", "user": {"login": "coder2020official", "id": 63740404, "node_id": "MDQ6VXNlcjYzNzQwNDA0", "avatar_url": "https://avatars.githubusercontent.com/u/63740404?v=4", "gravatar_id": "", "url": "https://api.github.com/users/coder2020official", "html_url": "https://github.com/coder2020official", "followers_url": "https://api.github.com/users/coder2020official/followers", "following_url": "https://api.github.com/users/coder2020official/following{/other_user}", "gists_url": "https://api.github.com/users/coder2020official/gists{/gist_id}", "starred_url": "https://api.github.com/users/coder2020official/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/coder2020official/subscriptions", "organizations_url": "https://api.github.com/users/coder2020official/orgs", "repos_url": "https://api.github.com/users/coder2020official/repos", "events_url": "https://api.github.com/users/coder2020official/events{/privacy}", "received_events_url": "https://api.github.com/users/coder2020official/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2022-12-13T14:45:14Z", "updated_at": "2022-12-19T13:17:12Z", "closed_at": "2022-12-19T13:17:12Z", "author_association": "COLLABORATOR", "active_lock_reason": null, "draft": false, "pull_request": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/pulls/1831", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1831", "diff_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1831.diff", "patch_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1831.patch", "merged_at": "2022-12-19T13:17:12Z"}, "body": "Fixed bad file descriptor and restart issue for windows", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1831/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1831/timeline", "performed_via_github_app": null, "state_reason": null}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1821", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1821/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1821/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1821/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/issues/1821", "id": 1471864957, "node_id": "I_kwDOAkVMUs5XuuB9", "number": 1821, "title": "TypeError: __init__() unexpected keyword argument 'caption_entities' for types.InputMediaPhoto(..., caption_entities=ents)", "user": {"login": "pavel555ru", "id": 39217586, "node_id": "MDQ6VXNlcjM5MjE3NTg2", "avatar_url": "https://avatars.githubusercontent.com/u/39217586?v=4", "gravatar_id": "", "url": "https://api.github.com/users/pavel555ru", "html_url": "https://github.com/pavel555ru", "followers_url": "https://api.github.com/users/pavel555ru/followers", "following_url": "https://api.github.com/users/pavel555ru/following{/other_user}", "gists_url": "https://api.github.com/users/pavel555ru/gists{/gist_id}", "starred_url": "https://api.github.com/users/pavel555ru/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/pavel555ru/subscriptions", "organizations_url": "https://api.github.com/users/pavel555ru/orgs", "repos_url": "https://api.github.com/users/pavel555ru/repos", "events_url": "https://api.github.com/users/pavel555ru/events{/privacy}", "received_events_url": "https://api.github.com/users/pavel555ru/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2022-12-01T19:52:52Z", "updated_at": "2022-12-02T20:53:00Z", "closed_at": "2022-12-02T20:53:00Z", "author_association": "NONE", "active_lock_reason": null, "body": "Please answer these questions before submitting your issue. Thanks!\r\n1. What version of pyTelegramBotAPI are you using? - 4.8.0\r\n2. What OS are you using? - Linux\r\n3. What version of python are you using? 3.8\r\n\r\nWhen creating InputMediaPhoto with caption_entities:\r\n`photo = telebot.types.InputMediaPhoto(my_file_id, caption=my_caption, caption_entities=my_entities)\r\n`\r\ngetting the below error:\r\n`TypeError: __init__() got an unexpected keyword argument 'caption_entities'`\r\n\r\nIf doing without caption_entities then works fine. Is caption_entities supported?", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1821/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1821/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1811", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1811/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1811/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1811/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1811", "id": 1465193560, "node_id": "PR_kwDOAkVMUs5DvZgd", "number": 1811, "title": "Continuehandling fix", "user": {"login": "coder2020official", "id": 63740404, "node_id": "MDQ6VXNlcjYzNzQwNDA0", "avatar_url": "https://avatars.githubusercontent.com/u/63740404?v=4", "gravatar_id": "", "url": "https://api.github.com/users/coder2020official", "html_url": "https://github.com/coder2020official", "followers_url": "https://api.github.com/users/coder2020official/followers", "following_url": "https://api.github.com/users/coder2020official/following{/other_user}", "gists_url": "https://api.github.com/users/coder2020official/gists{/gist_id}", "starred_url": "https://api.github.com/users/coder2020official/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/coder2020official/subscriptions", "organizations_url": "https://api.github.com/users/coder2020official/orgs", "repos_url": "https://api.github.com/users/coder2020official/repos", "events_url": "https://api.github.com/users/coder2020official/events{/privacy}", "received_events_url": "https://api.github.com/users/coder2020official/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}, {"id": 4419280578, "node_id": "LA_kwDOAkVMUs8AAAABB2jewg", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/confirmed", "name": "confirmed", "color": "1C7D1F", "default": false, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2022-11-26T16:09:27Z", "updated_at": "2022-11-27T08:30:38Z", "closed_at": "2022-11-27T08:30:38Z", "author_association": "COLLABORATOR", "active_lock_reason": null, "draft": false, "pull_request": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/pulls/1811", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1811", "diff_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1811.diff", "patch_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1811.patch", "merged_at": "2022-11-27T08:30:38Z"}, "body": "Made params local, so that it is unique for each handler. This bug is related to middlewares+continuehandling", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1811/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1811/timeline", "performed_via_github_app": null, "state_reason": null}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1808", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1808/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1808/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1808/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1808", "id": 1459998774, "node_id": "PR_kwDOAkVMUs5Dd5TF", "number": 1808, "title": "Fix #1804", "user": {"login": "coder2020official", "id": 63740404, "node_id": "MDQ6VXNlcjYzNzQwNDA0", "avatar_url": "https://avatars.githubusercontent.com/u/63740404?v=4", "gravatar_id": "", "url": "https://api.github.com/users/coder2020official", "html_url": "https://github.com/coder2020official", "followers_url": "https://api.github.com/users/coder2020official/followers", "following_url": "https://api.github.com/users/coder2020official/following{/other_user}", "gists_url": "https://api.github.com/users/coder2020official/gists{/gist_id}", "starred_url": "https://api.github.com/users/coder2020official/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/coder2020official/subscriptions", "organizations_url": "https://api.github.com/users/coder2020official/orgs", "repos_url": "https://api.github.com/users/coder2020official/repos", "events_url": "https://api.github.com/users/coder2020official/events{/privacy}", "received_events_url": "https://api.github.com/users/coder2020official/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}, {"id": 4419280578, "node_id": "LA_kwDOAkVMUs8AAAABB2jewg", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/confirmed", "name": "confirmed", "color": "1C7D1F", "default": false, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2022-11-22T14:37:44Z", "updated_at": "2022-11-26T16:05:01Z", "closed_at": "2022-11-26T16:05:01Z", "author_association": "COLLABORATOR", "active_lock_reason": null, "draft": false, "pull_request": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/pulls/1808", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1808", "diff_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1808.diff", "patch_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1808.patch", "merged_at": "2022-11-26T16:05:01Z"}, "body": "Fixes #1804 ", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1808/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1808/timeline", "performed_via_github_app": null, "state_reason": null}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1804", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1804/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1804/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1804/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/issues/1804", "id": 1458750227, "node_id": "I_kwDOAkVMUs5W8sMT", "number": 1804, "title": "Broken URL in 'html_text' attribute of message with HTML markup", "user": {"login": "dbzix", "id": 5552696, "node_id": "MDQ6VXNlcjU1NTI2OTY=", "avatar_url": "https://avatars.githubusercontent.com/u/5552696?v=4", "gravatar_id": "", "url": "https://api.github.com/users/dbzix", "html_url": "https://github.com/dbzix", "followers_url": "https://api.github.com/users/dbzix/followers", "following_url": "https://api.github.com/users/dbzix/following{/other_user}", "gists_url": "https://api.github.com/users/dbzix/gists{/gist_id}", "starred_url": "https://api.github.com/users/dbzix/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/dbzix/subscriptions", "organizations_url": "https://api.github.com/users/dbzix/orgs", "repos_url": "https://api.github.com/users/dbzix/repos", "events_url": "https://api.github.com/users/dbzix/events{/privacy}", "received_events_url": "https://api.github.com/users/dbzix/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}, {"id": 4448706514, "node_id": "LA_kwDOAkVMUs8AAAABCSnf0g", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/code", "name": "code", "color": "38C17E", "default": false, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2022-11-21T23:32:31Z", "updated_at": "2022-11-26T16:05:02Z", "closed_at": "2022-11-26T16:05:02Z", "author_association": "NONE", "active_lock_reason": null, "body": "Please answer these questions before submitting your issue. Thanks!\r\n\r\n1. What version of pyTelegramBotAPI are you using?\r\n4.7.1\r\n\r\n2. What OS are you using?\r\nGNU/Linux\r\n\r\n3. What version of python are you using?\r\nPython 3.10 / 3.11\r\n\r\n**Steps to reproduce**:\r\n1. Send message with HTML markup containing test word both in URL and in link's text:\r\n`<b><a href=\"https://www.some.address.here.org/TEST_WORD\">TEST_WORD</a></b>`\r\n\r\n2. Read **html_text** attribute of sent message - it's broken:\r\n`<a href=\"https://www.some.address.here.org/<b>TEST_WORD</b>\"><b>TEST_WORD</b></a>`\r\ninstead of just:\r\n`<a href=\"https://www.some.address.here.org/TEST_WORD\"><b>TEST_WORD</b></a>`\r\n\r\n3. Try to use updated at step 2 **html_text** for editing message or sending new message based on this content - you've got completely lost markup for this URL.\r\n\r\n**Note**:\r\nProblematic URL modification is part of processing nested entities in function `__html_text` of module `types.py`. Prior to version 4.7.1 there was no nested entities processing, so this issue relates to 4.7.1 only.", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1804/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1804/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1801", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1801/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1801/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1801/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1801", "id": 1455663289, "node_id": "PR_kwDOAkVMUs5DPO7G", "number": 1801, "title": "Fixed bot api bug", "user": {"login": "coder2020official", "id": 63740404, "node_id": "MDQ6VXNlcjYzNzQwNDA0", "avatar_url": "https://avatars.githubusercontent.com/u/63740404?v=4", "gravatar_id": "", "url": "https://api.github.com/users/coder2020official", "html_url": "https://github.com/coder2020official", "followers_url": "https://api.github.com/users/coder2020official/followers", "following_url": "https://api.github.com/users/coder2020official/following{/other_user}", "gists_url": "https://api.github.com/users/coder2020official/gists{/gist_id}", "starred_url": "https://api.github.com/users/coder2020official/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/coder2020official/subscriptions", "organizations_url": "https://api.github.com/users/coder2020official/orgs", "repos_url": "https://api.github.com/users/coder2020official/repos", "events_url": "https://api.github.com/users/coder2020official/events{/privacy}", "received_events_url": "https://api.github.com/users/coder2020official/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2022-11-18T19:13:29Z", "updated_at": "2022-11-18T19:22:39Z", "closed_at": "2022-11-18T19:22:39Z", "author_association": "COLLABORATOR", "active_lock_reason": null, "draft": false, "pull_request": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/pulls/1801", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1801", "diff_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1801.diff", "patch_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1801.patch", "merged_at": "2022-11-18T19:22:39Z"}, "body": null, "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1801/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1801/timeline", "performed_via_github_app": null, "state_reason": null}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1767", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1767/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1767/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1767/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/issues/1767", "id": 1425442669, "node_id": "I_kwDOAkVMUs5U9odt", "number": 1767, "title": "`debug` removed from uvicorn", "user": {"login": "batmanscode", "id": 29989939, "node_id": "MDQ6VXNlcjI5OTg5OTM5", "avatar_url": "https://avatars.githubusercontent.com/u/29989939?v=4", "gravatar_id": "", "url": "https://api.github.com/users/batmanscode", "html_url": "https://github.com/batmanscode", "followers_url": "https://api.github.com/users/batmanscode/followers", "following_url": "https://api.github.com/users/batmanscode/following{/other_user}", "gists_url": "https://api.github.com/users/batmanscode/gists{/gist_id}", "starred_url": "https://api.github.com/users/batmanscode/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/batmanscode/subscriptions", "organizations_url": "https://api.github.com/users/batmanscode/orgs", "repos_url": "https://api.github.com/users/batmanscode/repos", "events_url": "https://api.github.com/users/batmanscode/events{/privacy}", "received_events_url": "https://api.github.com/users/batmanscode/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2022-10-27T10:57:36Z", "updated_at": "2022-11-04T19:32:39Z", "closed_at": "2022-11-04T19:32:39Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Change in uvicorn: [Remove --debug flag #1640](https://github.com/encode/uvicorn/pull/1640)\r\n\r\n---\r\n\r\n`run_app()` https://github.com/eternnoir/pyTelegramBotAPI/blob/ebec3bf5c11cd685e1f3f031a422cfd831f7f428/telebot/ext/sync/webhooks.py#L107 and `run_webhooks()` https://github.com/eternnoir/pyTelegramBotAPI/blob/ebec3bf5c11cd685e1f3f031a422cfd831f7f428/telebot/__init__.py#L441 will need to be updated.", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1767/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1767/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1761", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1761/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1761/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1761/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1761", "id": 1419426684, "node_id": "PR_kwDOAkVMUs5BV9Av", "number": 1761, "title": "Extended exception handler behaviour for async", "user": {"login": "coder2020official", "id": 63740404, "node_id": "MDQ6VXNlcjYzNzQwNDA0", "avatar_url": "https://avatars.githubusercontent.com/u/63740404?v=4", "gravatar_id": "", "url": "https://api.github.com/users/coder2020official", "html_url": "https://github.com/coder2020official", "followers_url": "https://api.github.com/users/coder2020official/followers", "following_url": "https://api.github.com/users/coder2020official/following{/other_user}", "gists_url": "https://api.github.com/users/coder2020official/gists{/gist_id}", "starred_url": "https://api.github.com/users/coder2020official/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/coder2020official/subscriptions", "organizations_url": "https://api.github.com/users/coder2020official/orgs", "repos_url": "https://api.github.com/users/coder2020official/repos", "events_url": "https://api.github.com/users/coder2020official/events{/privacy}", "received_events_url": "https://api.github.com/users/coder2020official/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}, {"id": 4419280578, "node_id": "LA_kwDOAkVMUs8AAAABB2jewg", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/confirmed", "name": "confirmed", "color": "1C7D1F", "default": false, "description": ""}, {"id": 4448706514, "node_id": "LA_kwDOAkVMUs8AAAABCSnf0g", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/code", "name": "code", "color": "38C17E", "default": false, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2022-10-22T17:50:19Z", "updated_at": "2022-11-06T06:23:02Z", "closed_at": "2022-11-06T06:23:02Z", "author_association": "COLLABORATOR", "active_lock_reason": null, "draft": false, "pull_request": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/pulls/1761", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1761", "diff_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1761.diff", "patch_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1761.patch", "merged_at": "2022-11-06T06:23:02Z"}, "body": null, "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1761/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1761/timeline", "performed_via_github_app": null, "state_reason": null}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1749", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1749/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1749/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1749/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1749", "id": 1402058409, "node_id": "PR_kwDOAkVMUs5AcE68", "number": 1749, "title": "Check CUSTOM_REQUEST_SENDER before RETRY_xxx.", "user": {"login": "Badiboy", "id": 5613421, "node_id": "MDQ6VXNlcjU2MTM0MjE=", "avatar_url": "https://avatars.githubusercontent.com/u/5613421?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Badiboy", "html_url": "https://github.com/Badiboy", "followers_url": "https://api.github.com/users/Badiboy/followers", "following_url": "https://api.github.com/users/Badiboy/following{/other_user}", "gists_url": "https://api.github.com/users/Badiboy/gists{/gist_id}", "starred_url": "https://api.github.com/users/Badiboy/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Badiboy/subscriptions", "organizations_url": "https://api.github.com/users/Badiboy/orgs", "repos_url": "https://api.github.com/users/Badiboy/repos", "events_url": "https://api.github.com/users/Badiboy/events{/privacy}", "received_events_url": "https://api.github.com/users/Badiboy/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}, {"id": 4419280578, "node_id": "LA_kwDOAkVMUs8AAAABB2jewg", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/confirmed", "name": "confirmed", "color": "1C7D1F", "default": false, "description": ""}, {"id": 4448706514, "node_id": "LA_kwDOAkVMUs8AAAABCSnf0g", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/code", "name": "code", "color": "38C17E", "default": false, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2022-10-08T20:42:43Z", "updated_at": "2022-10-09T16:08:45Z", "closed_at": "2022-10-08T20:43:44Z", "author_association": "COLLABORATOR", "active_lock_reason": null, "draft": false, "pull_request": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/pulls/1749", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1749", "diff_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1749.diff", "patch_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1749.patch", "merged_at": "2022-10-08T20:43:44Z"}, "body": "## Description\r\nCheck CUSTOM_REQUEST_SENDER before RETRY_xxx.\r\n\r\n## Checklist:\r\n- [x] My changes won't break backward compatibility\r\n", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1749/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1749/timeline", "performed_via_github_app": null, "state_reason": null}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1747", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1747/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1747/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1747/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1747", "id": 1401500935, "node_id": "PR_kwDOAkVMUs5AaVro", "number": 1747, "title": "Update __init__.py", "user": {"login": "coder2020official", "id": 63740404, "node_id": "MDQ6VXNlcjYzNzQwNDA0", "avatar_url": "https://avatars.githubusercontent.com/u/63740404?v=4", "gravatar_id": "", "url": "https://api.github.com/users/coder2020official", "html_url": "https://github.com/coder2020official", "followers_url": "https://api.github.com/users/coder2020official/followers", "following_url": "https://api.github.com/users/coder2020official/following{/other_user}", "gists_url": "https://api.github.com/users/coder2020official/gists{/gist_id}", "starred_url": "https://api.github.com/users/coder2020official/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/coder2020official/subscriptions", "organizations_url": "https://api.github.com/users/coder2020official/orgs", "repos_url": "https://api.github.com/users/coder2020official/repos", "events_url": "https://api.github.com/users/coder2020official/events{/privacy}", "received_events_url": "https://api.github.com/users/coder2020official/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}, {"id": 4419280578, "node_id": "LA_kwDOAkVMUs8AAAABB2jewg", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/confirmed", "name": "confirmed", "color": "1C7D1F", "default": false, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2022-10-07T17:51:47Z", "updated_at": "2022-10-07T17:57:50Z", "closed_at": "2022-10-07T17:57:50Z", "author_association": "COLLABORATOR", "active_lock_reason": null, "draft": false, "pull_request": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/pulls/1747", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1747", "diff_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1747.diff", "patch_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1747.patch", "merged_at": "2022-10-07T17:57:50Z"}, "body": "Fixes #1743 ", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1747/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1747/timeline", "performed_via_github_app": null, "state_reason": null}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1743", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1743/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1743/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1743/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/issues/1743", "id": 1396534695, "node_id": "I_kwDOAkVMUs5TPW2n", "number": 1743, "title": "Formatting utility error", "user": {"login": "nrc4cyber", "id": 78347353, "node_id": "MDQ6VXNlcjc4MzQ3MzUz", "avatar_url": "https://avatars.githubusercontent.com/u/78347353?v=4", "gravatar_id": "", "url": "https://api.github.com/users/nrc4cyber", "html_url": "https://github.com/nrc4cyber", "followers_url": "https://api.github.com/users/nrc4cyber/followers", "following_url": "https://api.github.com/users/nrc4cyber/following{/other_user}", "gists_url": "https://api.github.com/users/nrc4cyber/gists{/gist_id}", "starred_url": "https://api.github.com/users/nrc4cyber/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/nrc4cyber/subscriptions", "organizations_url": "https://api.github.com/users/nrc4cyber/orgs", "repos_url": "https://api.github.com/users/nrc4cyber/repos", "events_url": "https://api.github.com/users/nrc4cyber/events{/privacy}", "received_events_url": "https://api.github.com/users/nrc4cyber/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}, {"id": 4419280578, "node_id": "LA_kwDOAkVMUs8AAAABB2jewg", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/confirmed", "name": "confirmed", "color": "1C7D1F", "default": false, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2022-10-04T16:16:39Z", "updated_at": "2022-10-07T17:57:50Z", "closed_at": "2022-10-07T17:57:50Z", "author_association": "NONE", "active_lock_reason": null, "body": "Please answer these questions before submitting your issue. Thanks!\r\n\r\n1. What version of pyTelegramBotAPI are you using?\r\n`4.7.0`\r\n\r\n3. What OS are you using?\r\nTried both on `Ubuntu 20.04.4` and `macOS 12.3 21E230 arm64`\r\n\r\n4. What version of python are you using?\r\n`Python 3.10.4`\r\n\r\n\r\nTrying to use [telebot.formatting.escape_markdown](https://pytba.readthedocs.io/en/latest/formatting.html#telebot.formatting.escape_html) like so\r\n```python\r\n>>> import telebot\r\n>>> print(telebot.formatting.escape_markdown(\"This is some text that needs(!) to be escaped!.\"))\r\n```\r\nraises the exception\r\n```python\r\n>>> import telebot\r\n>>> print(telebot.formatting.escape_markdown(\"This is some text that needs(!) to be escaped!.\"))\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\nAttributeError: module 'telebot' has no attribute 'formatting'. Did you mean: 'formatter'?\r\n>>>\r\n```\r\n\r\nI am though able to import just formatting like so\r\n```python\r\n>>> from telebot import formatting\r\n>>> print(formatting.escape_markdown(\"This is some text that needs(!) to be escaped!.\"))\r\n# Output: This is some text that needs\\(\\!\\) to be escaped\\!\\.\r\n```\r\nand importing formatting on its own also then allows\r\n``` python\r\n>>> from telebot import formatting\r\n>>> import telebot\r\n>>> print(telebot.formatting.escape_markdown(\"This is some text that needs(!) to be escaped!.\"))\r\n# Output: This is some text that needs\\(\\!\\) to be escaped\\!\\.\r\n```", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1743/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1743/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1730", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1730/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1730/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1730/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/issues/1730", "id": 1379786247, "node_id": "I_kwDOAkVMUs5SPd4H", "number": 1730, "title": "bot infinity polling can't handle errors or at least some of them", "user": {"login": "daemoncreator", "id": 113966669, "node_id": "U_kgDOBsr-TQ", "avatar_url": "https://avatars.githubusercontent.com/u/113966669?v=4", "gravatar_id": "", "url": "https://api.github.com/users/daemoncreator", "html_url": "https://github.com/daemoncreator", "followers_url": "https://api.github.com/users/daemoncreator/followers", "following_url": "https://api.github.com/users/daemoncreator/following{/other_user}", "gists_url": "https://api.github.com/users/daemoncreator/gists{/gist_id}", "starred_url": "https://api.github.com/users/daemoncreator/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/daemoncreator/subscriptions", "organizations_url": "https://api.github.com/users/daemoncreator/orgs", "repos_url": "https://api.github.com/users/daemoncreator/repos", "events_url": "https://api.github.com/users/daemoncreator/events{/privacy}", "received_events_url": "https://api.github.com/users/daemoncreator/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}, {"id": 4419298645, "node_id": "LA_kwDOAkVMUs8AAAABB2klVQ", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/not%20confirmed", "name": "not confirmed", "color": "C43702", "default": false, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 5, "created_at": "2022-09-20T17:51:53Z", "updated_at": "2022-09-21T16:28:13Z", "closed_at": "2022-09-21T16:28:13Z", "author_association": "NONE", "active_lock_reason": null, "body": "Please answer these questions before submitting your issue. Thanks!\r\n\r\n1. What version of pyTelegramBotAPI are you using? last one\r\n\r\n2. What OS are you using? Windows\r\n\r\n4. What version of python are you using? 3.8.5\r\n\r\n\r\nI was using bot infinity polling but it stops my script when an error come \r\n\r\n\"telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400 Description: Bad Request: can't restrict self\r\n\"\r\n2022-09-20 19:22:49,671 (__init__.py:455 MainThread) ERROR - TeleBot: \"A request to the Telegram API was unsuccessful. Error code: 400 Description: Bad Request: can't restrict self\"\"\r\n(I tried to mute myself while being the chat owner)\r\n\r\nNow I'm using this code and it doesnt give me any problems\r\n\"try:\r\n    bot.polling(none_stop=True)\r\nexcept Exception as e:\r\n    time.sleep(15)\" ", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1730/reactions", "total_count": 1, "+1": 1, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1730/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1723", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1723/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1723/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1723/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1723", "id": 1376720678, "node_id": "PR_kwDOAkVMUs4_I3Sj", "number": 1723, "title": "don't block loop", "user": {"login": "byehack", "id": 26390254, "node_id": "MDQ6VXNlcjI2MzkwMjU0", "avatar_url": "https://avatars.githubusercontent.com/u/26390254?v=4", "gravatar_id": "", "url": "https://api.github.com/users/byehack", "html_url": "https://github.com/byehack", "followers_url": "https://api.github.com/users/byehack/followers", "following_url": "https://api.github.com/users/byehack/following{/other_user}", "gists_url": "https://api.github.com/users/byehack/gists{/gist_id}", "starred_url": "https://api.github.com/users/byehack/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/byehack/subscriptions", "organizations_url": "https://api.github.com/users/byehack/orgs", "repos_url": "https://api.github.com/users/byehack/repos", "events_url": "https://api.github.com/users/byehack/events{/privacy}", "received_events_url": "https://api.github.com/users/byehack/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2022-09-17T09:28:29Z", "updated_at": "2022-09-17T09:42:58Z", "closed_at": "2022-09-17T09:42:58Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "draft": false, "pull_request": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/pulls/1723", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1723", "diff_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1723.diff", "patch_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1723.patch", "merged_at": "2022-09-17T09:42:58Z"}, "body": null, "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1723/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1723/timeline", "performed_via_github_app": null, "state_reason": null}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1710", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1710/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1710/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1710/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1710", "id": 1368581292, "node_id": "PR_kwDOAkVMUs4-t4tE", "number": 1710, "title": "Fixed difference between request_timeout and timeout.", "user": {"login": "coder2020official", "id": 63740404, "node_id": "MDQ6VXNlcjYzNzQwNDA0", "avatar_url": "https://avatars.githubusercontent.com/u/63740404?v=4", "gravatar_id": "", "url": "https://api.github.com/users/coder2020official", "html_url": "https://github.com/coder2020official", "followers_url": "https://api.github.com/users/coder2020official/followers", "following_url": "https://api.github.com/users/coder2020official/following{/other_user}", "gists_url": "https://api.github.com/users/coder2020official/gists{/gist_id}", "starred_url": "https://api.github.com/users/coder2020official/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/coder2020official/subscriptions", "organizations_url": "https://api.github.com/users/coder2020official/orgs", "repos_url": "https://api.github.com/users/coder2020official/repos", "events_url": "https://api.github.com/users/coder2020official/events{/privacy}", "received_events_url": "https://api.github.com/users/coder2020official/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}, {"id": 229170314, "node_id": "MDU6TGFiZWwyMjkxNzAzMTQ=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/help%20wanted", "name": "help wanted", "color": "159818", "default": true, "description": null}, {"id": 4419280578, "node_id": "LA_kwDOAkVMUs8AAAABB2jewg", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/confirmed", "name": "confirmed", "color": "1C7D1F", "default": false, "description": ""}, {"id": 4448706514, "node_id": "LA_kwDOAkVMUs8AAAABCSnf0g", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/code", "name": "code", "color": "38C17E", "default": false, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2022-09-10T10:36:03Z", "updated_at": "2022-09-10T16:48:31Z", "closed_at": "2022-09-10T16:48:31Z", "author_association": "COLLABORATOR", "active_lock_reason": null, "draft": false, "pull_request": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/pulls/1710", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1710", "diff_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1710.diff", "patch_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1710.patch", "merged_at": "2022-09-10T16:48:31Z"}, "body": "## Description\r\ngetUpdates parameter may contain 2 parameters: request_timeout & timeout. other methods may contain timeout parameter that should be applied to ClientTimeout.", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1710/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1710/timeline", "performed_via_github_app": null, "state_reason": null}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1703", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1703/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1703/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1703/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1703", "id": 1364936866, "node_id": "PR_kwDOAkVMUs4-howU", "number": 1703, "title": "Fix #1702", "user": {"login": "coder2020official", "id": 63740404, "node_id": "MDQ6VXNlcjYzNzQwNDA0", "avatar_url": "https://avatars.githubusercontent.com/u/63740404?v=4", "gravatar_id": "", "url": "https://api.github.com/users/coder2020official", "html_url": "https://github.com/coder2020official", "followers_url": "https://api.github.com/users/coder2020official/followers", "following_url": "https://api.github.com/users/coder2020official/following{/other_user}", "gists_url": "https://api.github.com/users/coder2020official/gists{/gist_id}", "starred_url": "https://api.github.com/users/coder2020official/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/coder2020official/subscriptions", "organizations_url": "https://api.github.com/users/coder2020official/orgs", "repos_url": "https://api.github.com/users/coder2020official/repos", "events_url": "https://api.github.com/users/coder2020official/events{/privacy}", "received_events_url": "https://api.github.com/users/coder2020official/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}, {"id": 4419280578, "node_id": "LA_kwDOAkVMUs8AAAABB2jewg", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/confirmed", "name": "confirmed", "color": "1C7D1F", "default": false, "description": ""}, {"id": 4491563720, "node_id": "LA_kwDOAkVMUs8AAAABC7fSyA", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/under%20testing", "name": "under testing", "color": "C10BA5", "default": false, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2022-09-07T16:46:23Z", "updated_at": "2022-09-09T17:09:26Z", "closed_at": "2022-09-09T17:09:25Z", "author_association": "COLLABORATOR", "active_lock_reason": null, "draft": false, "pull_request": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/pulls/1703", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1703", "diff_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1703.diff", "patch_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1703.patch", "merged_at": "2022-09-09T17:09:25Z"}, "body": null, "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1703/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1703/timeline", "performed_via_github_app": null, "state_reason": null}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1702", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1702/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1702/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1702/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/issues/1702", "id": 1364725995, "node_id": "I_kwDOAkVMUs5RWBDr", "number": 1702, "title": "bot.download_file causes Aiohttp ClientError: ClientOSError on the next message", "user": {"login": "yudytskiy", "id": 69458777, "node_id": "MDQ6VXNlcjY5NDU4Nzc3", "avatar_url": "https://avatars.githubusercontent.com/u/69458777?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yudytskiy", "html_url": "https://github.com/yudytskiy", "followers_url": "https://api.github.com/users/yudytskiy/followers", "following_url": "https://api.github.com/users/yudytskiy/following{/other_user}", "gists_url": "https://api.github.com/users/yudytskiy/gists{/gist_id}", "starred_url": "https://api.github.com/users/yudytskiy/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yudytskiy/subscriptions", "organizations_url": "https://api.github.com/users/yudytskiy/orgs", "repos_url": "https://api.github.com/users/yudytskiy/repos", "events_url": "https://api.github.com/users/yudytskiy/events{/privacy}", "received_events_url": "https://api.github.com/users/yudytskiy/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}, {"id": 3969571989, "node_id": "LA_kwDOAkVMUs7smtyV", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/comming%20soon", "name": "comming soon", "color": "E8900A", "default": false, "description": ""}, {"id": 4419280578, "node_id": "LA_kwDOAkVMUs8AAAABB2jewg", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/confirmed", "name": "confirmed", "color": "1C7D1F", "default": false, "description": ""}, {"id": 4448706514, "node_id": "LA_kwDOAkVMUs8AAAABCSnf0g", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/code", "name": "code", "color": "38C17E", "default": false, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 5, "created_at": "2022-09-07T14:07:51Z", "updated_at": "2022-09-09T17:09:08Z", "closed_at": "2022-09-09T17:09:08Z", "author_association": "NONE", "active_lock_reason": null, "body": "Please answer these questions before submitting your issue. Thanks!\r\n\r\n1. What version of pyTelegramBotAPI are you using?\r\n4.6.0, 4.6.1, 4.7.0\r\n2. What OS are you using?\r\nwin, lin\r\n3. What version of python are you using?\r\n3.10\r\n\r\nHi.\r\nHere is small bot demonstrates the problem:\r\n```\r\nimport asyncio\r\nfrom telebot.async_telebot import AsyncTeleBot\r\n\r\nTOKEN = '**********'\r\nbot = AsyncTeleBot(TOKEN)\r\n\r\n@bot.message_handler(commands=['id'])\r\nasync def id_command(message):\r\n    return await bot.reply_to(message, text=f'Your id: {message.chat.id}')\r\n\r\n@bot.message_handler(content_types=['photo'])\r\nasync def photo_handler(message):\r\n    file_id = message.photo[-1].file_id\r\n    file_info = await bot.get_file(file_id)\r\n    # This download method causes:\r\n    # Aiohttp ClientError: ClientOSError and then\r\n    # Request timeout. Request: .... and then\r\n    # Infinity polling: polling exited\r\n    # on the next message \r\n    _file = await bot.download_file(file_info.file_path)\r\n    return await bot.reply_to(message, f'Path: {file_info.file_path}; Length:{len(_file)}' )\r\n\r\nif __name__ == '__main__':\r\n    loop = asyncio.new_event_loop()\r\n    # Not recovering with infinity_polling: await self._process_polling(non_stop=False....\r\n    # Version 4.6.0 recovering after Aiohttp ClientError\r\n    # Version 4.6.1 and 4.7.0 not recovering\r\n    loop.create_task(bot.infinity_polling())\r\n    # Recovering:\r\n    # loop.create_task(bot.polling(non_stop=True))\r\n    loop.run_forever()\r\n\r\n# The scenario:\r\n# - bot is run\r\n# - send /id command and get reply\r\n# - send any image file and get the filename and file length\r\n# - send /id and get polling exited with:\r\n# (asyncio_helper.py:80 MainThread) ERROR - TeleBot: \"Aiohttp ClientError: ClientOSError\"\r\n# (async_telebot.py:317 MainThread) ERROR - TeleBot: \"Request timeout. Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x0000025A91E391E0> files=None request_timeout=None\"\r\n# (async_telebot.py:276 MainThread) ERROR - TeleBot: \"Infinity polling: polling exited\"\r\n# (async_telebot.py:278 MainThread) ERROR - TeleBot: \"Break infinity polling\"\r\n```", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1702/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1702/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1695", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1695/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1695/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1695/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1695", "id": 1358456747, "node_id": "PR_kwDOAkVMUs4-MM_2", "number": 1695, "title": "Fix timeout usage in AsyncTeleBot", "user": {"login": "Badiboy", "id": 5613421, "node_id": "MDQ6VXNlcjU2MTM0MjE=", "avatar_url": "https://avatars.githubusercontent.com/u/5613421?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Badiboy", "html_url": "https://github.com/Badiboy", "followers_url": "https://api.github.com/users/Badiboy/followers", "following_url": "https://api.github.com/users/Badiboy/following{/other_user}", "gists_url": "https://api.github.com/users/Badiboy/gists{/gist_id}", "starred_url": "https://api.github.com/users/Badiboy/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Badiboy/subscriptions", "organizations_url": "https://api.github.com/users/Badiboy/orgs", "repos_url": "https://api.github.com/users/Badiboy/repos", "events_url": "https://api.github.com/users/Badiboy/events{/privacy}", "received_events_url": "https://api.github.com/users/Badiboy/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}, {"id": 229170313, "node_id": "MDU6TGFiZWwyMjkxNzAzMTM=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/enhancement", "name": "enhancement", "color": "84b6eb", "default": true, "description": null}, {"id": 229170314, "node_id": "MDU6TGFiZWwyMjkxNzAzMTQ=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/help%20wanted", "name": "help wanted", "color": "159818", "default": true, "description": null}, {"id": 4420195750, "node_id": "LA_kwDOAkVMUs8AAAABB3bVpg", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bot%20api", "name": "bot api", "color": "85B153", "default": false, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2022-09-01T08:27:07Z", "updated_at": "2022-09-10T12:03:22Z", "closed_at": "2022-09-10T12:03:22Z", "author_association": "COLLABORATOR", "active_lock_reason": null, "draft": false, "pull_request": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/pulls/1695", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1695", "diff_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1695.diff", "patch_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1695.patch", "merged_at": null}, "body": "## Description\r\n_timeout_ parameter of API functions was ignored in Async version.\r\n\r\nAlternative fix for request: https://github.com/eternnoir/pyTelegramBotAPI/pull/1694\r\n", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1695/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1695/timeline", "performed_via_github_app": null, "state_reason": null}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1675", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1675/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1675/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1675/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1675", "id": 1340618146, "node_id": "PR_kwDOAkVMUs49Q8tp", "number": 1675, "title": "Fixed #1650", "user": {"login": "coder2020official", "id": 63740404, "node_id": "MDQ6VXNlcjYzNzQwNDA0", "avatar_url": "https://avatars.githubusercontent.com/u/63740404?v=4", "gravatar_id": "", "url": "https://api.github.com/users/coder2020official", "html_url": "https://github.com/coder2020official", "followers_url": "https://api.github.com/users/coder2020official/followers", "following_url": "https://api.github.com/users/coder2020official/following{/other_user}", "gists_url": "https://api.github.com/users/coder2020official/gists{/gist_id}", "starred_url": "https://api.github.com/users/coder2020official/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/coder2020official/subscriptions", "organizations_url": "https://api.github.com/users/coder2020official/orgs", "repos_url": "https://api.github.com/users/coder2020official/repos", "events_url": "https://api.github.com/users/coder2020official/events{/privacy}", "received_events_url": "https://api.github.com/users/coder2020official/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}, {"id": 229170313, "node_id": "MDU6TGFiZWwyMjkxNzAzMTM=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/enhancement", "name": "enhancement", "color": "84b6eb", "default": true, "description": null}, {"id": 4420195750, "node_id": "LA_kwDOAkVMUs8AAAABB3bVpg", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bot%20api", "name": "bot api", "color": "85B153", "default": false, "description": ""}, {"id": 4427858923, "node_id": "LA_kwDOAkVMUs8AAAABB-vD6w", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/under%20discussion", "name": "under discussion", "color": "FFFF00", "default": false, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2022-08-16T16:41:35Z", "updated_at": "2022-08-16T21:38:59Z", "closed_at": "2022-08-16T21:38:59Z", "author_association": "COLLABORATOR", "active_lock_reason": null, "draft": false, "pull_request": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/pulls/1675", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1675", "diff_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1675.diff", "patch_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1675.patch", "merged_at": "2022-08-16T21:38:59Z"}, "body": "## Description\r\nInclude changes, new features and etc:\r\nFixed issue #1650\r\n\r\n## Describe your tests\r\nHow did you test your change?\r\nI tried to send different posts with bunch of entities. \r\n\r\nPython version: 3.10.2\r\n\r\nOS: Windows 10\r\n\r\n## Checklist:\r\n- [ ] I added/edited example on new feature/change (if exists)\r\n- [x] My changes won't break backward compatibility\r\n- [x] I made changes both for sync and async\r\n", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1675/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1675/timeline", "performed_via_github_app": null, "state_reason": null}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1668", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1668/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1668/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1668/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1668", "id": 1337919627, "node_id": "PR_kwDOAkVMUs49IM9g", "number": 1668, "title": "Update asyncio_helper.py", "user": {"login": "coder2020official", "id": 63740404, "node_id": "MDQ6VXNlcjYzNzQwNDA0", "avatar_url": "https://avatars.githubusercontent.com/u/63740404?v=4", "gravatar_id": "", "url": "https://api.github.com/users/coder2020official", "html_url": "https://github.com/coder2020official", "followers_url": "https://api.github.com/users/coder2020official/followers", "following_url": "https://api.github.com/users/coder2020official/following{/other_user}", "gists_url": "https://api.github.com/users/coder2020official/gists{/gist_id}", "starred_url": "https://api.github.com/users/coder2020official/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/coder2020official/subscriptions", "organizations_url": "https://api.github.com/users/coder2020official/orgs", "repos_url": "https://api.github.com/users/coder2020official/repos", "events_url": "https://api.github.com/users/coder2020official/events{/privacy}", "received_events_url": "https://api.github.com/users/coder2020official/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}, {"id": 4420195750, "node_id": "LA_kwDOAkVMUs8AAAABB3bVpg", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bot%20api", "name": "bot api", "color": "85B153", "default": false, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2022-08-13T10:00:16Z", "updated_at": "2022-08-13T10:23:53Z", "closed_at": "2022-08-13T10:03:47Z", "author_association": "COLLABORATOR", "active_lock_reason": null, "draft": false, "pull_request": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/pulls/1668", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1668", "diff_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1668.diff", "patch_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1668.patch", "merged_at": "2022-08-13T10:03:47Z"}, "body": "## Description\r\nInclude changes, new features and etc:\r\n\r\n## Describe your tests\r\nHow did you test your change?\r\n\r\nPython version:\r\n\r\nOS:\r\n\r\n## Checklist:\r\n- [ ] I added/edited example on new feature/change (if exists)\r\n- [ ] My changes won't break backward compatibility\r\n- [ ] I made changes both for sync and async\r\n", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1668/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1668/timeline", "performed_via_github_app": null, "state_reason": null}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1666", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1666/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1666/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1666/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1666", "id": 1337919226, "node_id": "PR_kwDOAkVMUs49IM5F", "number": 1666, "title": "Update async_telebot.py", "user": {"login": "coder2020official", "id": 63740404, "node_id": "MDQ6VXNlcjYzNzQwNDA0", "avatar_url": "https://avatars.githubusercontent.com/u/63740404?v=4", "gravatar_id": "", "url": "https://api.github.com/users/coder2020official", "html_url": "https://github.com/coder2020official", "followers_url": "https://api.github.com/users/coder2020official/followers", "following_url": "https://api.github.com/users/coder2020official/following{/other_user}", "gists_url": "https://api.github.com/users/coder2020official/gists{/gist_id}", "starred_url": "https://api.github.com/users/coder2020official/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/coder2020official/subscriptions", "organizations_url": "https://api.github.com/users/coder2020official/orgs", "repos_url": "https://api.github.com/users/coder2020official/repos", "events_url": "https://api.github.com/users/coder2020official/events{/privacy}", "received_events_url": "https://api.github.com/users/coder2020official/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2022-08-13T09:58:03Z", "updated_at": "2022-08-13T10:23:06Z", "closed_at": "2022-08-13T09:58:12Z", "author_association": "COLLABORATOR", "active_lock_reason": null, "draft": false, "pull_request": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/pulls/1666", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1666", "diff_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1666.diff", "patch_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/1666.patch", "merged_at": "2022-08-13T09:58:11Z"}, "body": "## Description\r\nInclude changes, new features and etc:\r\n\r\n## Describe your tests\r\nHow did you test your change?\r\n\r\nPython version:\r\n\r\nOS:\r\n\r\n## Checklist:\r\n- [ ] I added/edited example on new feature/change (if exists)\r\n- [ ] My changes won't break backward compatibility\r\n- [ ] I made changes both for sync and async\r\n", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1666/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1666/timeline", "performed_via_github_app": null, "state_reason": null}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1650", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1650/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1650/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1650/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/issues/1650", "id": 1323301300, "node_id": "I_kwDOAkVMUs5O3_m0", "number": 1650, "title": "message.html_text cannot return correct result", "user": {"login": "ImJoke", "id": 55929550, "node_id": "MDQ6VXNlcjU1OTI5NTUw", "avatar_url": "https://avatars.githubusercontent.com/u/55929550?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ImJoke", "html_url": "https://github.com/ImJoke", "followers_url": "https://api.github.com/users/ImJoke/followers", "following_url": "https://api.github.com/users/ImJoke/following{/other_user}", "gists_url": "https://api.github.com/users/ImJoke/gists{/gist_id}", "starred_url": "https://api.github.com/users/ImJoke/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ImJoke/subscriptions", "organizations_url": "https://api.github.com/users/ImJoke/orgs", "repos_url": "https://api.github.com/users/ImJoke/repos", "events_url": "https://api.github.com/users/ImJoke/events{/privacy}", "received_events_url": "https://api.github.com/users/ImJoke/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}, {"id": 229170313, "node_id": "MDU6TGFiZWwyMjkxNzAzMTM=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/enhancement", "name": "enhancement", "color": "84b6eb", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": {"login": "coder2020official", "id": 63740404, "node_id": "MDQ6VXNlcjYzNzQwNDA0", "avatar_url": "https://avatars.githubusercontent.com/u/63740404?v=4", "gravatar_id": "", "url": "https://api.github.com/users/coder2020official", "html_url": "https://github.com/coder2020official", "followers_url": "https://api.github.com/users/coder2020official/followers", "following_url": "https://api.github.com/users/coder2020official/following{/other_user}", "gists_url": "https://api.github.com/users/coder2020official/gists{/gist_id}", "starred_url": "https://api.github.com/users/coder2020official/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/coder2020official/subscriptions", "organizations_url": "https://api.github.com/users/coder2020official/orgs", "repos_url": "https://api.github.com/users/coder2020official/repos", "events_url": "https://api.github.com/users/coder2020official/events{/privacy}", "received_events_url": "https://api.github.com/users/coder2020official/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "coder2020official", "id": 63740404, "node_id": "MDQ6VXNlcjYzNzQwNDA0", "avatar_url": "https://avatars.githubusercontent.com/u/63740404?v=4", "gravatar_id": "", "url": "https://api.github.com/users/coder2020official", "html_url": "https://github.com/coder2020official", "followers_url": "https://api.github.com/users/coder2020official/followers", "following_url": "https://api.github.com/users/coder2020official/following{/other_user}", "gists_url": "https://api.github.com/users/coder2020official/gists{/gist_id}", "starred_url": "https://api.github.com/users/coder2020official/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/coder2020official/subscriptions", "organizations_url": "https://api.github.com/users/coder2020official/orgs", "repos_url": "https://api.github.com/users/coder2020official/repos", "events_url": "https://api.github.com/users/coder2020official/events{/privacy}", "received_events_url": "https://api.github.com/users/coder2020official/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 5, "created_at": "2022-07-30T21:32:03Z", "updated_at": "2022-08-16T21:39:00Z", "closed_at": "2022-08-16T21:39:00Z", "author_association": "NONE", "active_lock_reason": null, "body": "Please answer these questions before submitting your issue. Thanks!\r\n\r\n1. What version of pyTelegramBotAPI are you using? 4.6.1\r\n2. What OS are you using? Windows 10\r\n3. What version of python are you using? Python 3.10.5\r\n\r\n\r\n### So I typed qwertyuiop with bold, italic and underline formatting, but only bold came back\r\n\r\n![image](https://user-images.githubusercontent.com/55929550/181996718-26458d8e-a38a-4dd8-90ce-708f044ab46c.png)\r\n![image](https://user-images.githubusercontent.com/55929550/181996736-c6438db3-995a-415b-906f-e58912572701.png)\r\n", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1650/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1650/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1530", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1530/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1530/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1530/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/issues/1530", "id": 1225221539, "node_id": "I_kwDOAkVMUs5JB2Wj", "number": 1530, "title": "Concurrency error related to storages", "user": {"login": "coder2020official", "id": 63740404, "node_id": "MDQ6VXNlcjYzNzQwNDA0", "avatar_url": "https://avatars.githubusercontent.com/u/63740404?v=4", "gravatar_id": "", "url": "https://api.github.com/users/coder2020official", "html_url": "https://github.com/coder2020official", "followers_url": "https://api.github.com/users/coder2020official/followers", "following_url": "https://api.github.com/users/coder2020official/following{/other_user}", "gists_url": "https://api.github.com/users/coder2020official/gists{/gist_id}", "starred_url": "https://api.github.com/users/coder2020official/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/coder2020official/subscriptions", "organizations_url": "https://api.github.com/users/coder2020official/orgs", "repos_url": "https://api.github.com/users/coder2020official/repos", "events_url": "https://api.github.com/users/coder2020official/events{/privacy}", "received_events_url": "https://api.github.com/users/coder2020official/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}, {"id": 4419298645, "node_id": "LA_kwDOAkVMUs8AAAABB2klVQ", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/not%20confirmed", "name": "not confirmed", "color": "C43702", "default": false, "description": ""}], "state": "closed", "locked": false, "assignee": {"login": "coder2020official", "id": 63740404, "node_id": "MDQ6VXNlcjYzNzQwNDA0", "avatar_url": "https://avatars.githubusercontent.com/u/63740404?v=4", "gravatar_id": "", "url": "https://api.github.com/users/coder2020official", "html_url": "https://github.com/coder2020official", "followers_url": "https://api.github.com/users/coder2020official/followers", "following_url": "https://api.github.com/users/coder2020official/following{/other_user}", "gists_url": "https://api.github.com/users/coder2020official/gists{/gist_id}", "starred_url": "https://api.github.com/users/coder2020official/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/coder2020official/subscriptions", "organizations_url": "https://api.github.com/users/coder2020official/orgs", "repos_url": "https://api.github.com/users/coder2020official/repos", "events_url": "https://api.github.com/users/coder2020official/events{/privacy}", "received_events_url": "https://api.github.com/users/coder2020official/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "coder2020official", "id": 63740404, "node_id": "MDQ6VXNlcjYzNzQwNDA0", "avatar_url": "https://avatars.githubusercontent.com/u/63740404?v=4", "gravatar_id": "", "url": "https://api.github.com/users/coder2020official", "html_url": "https://github.com/coder2020official", "followers_url": "https://api.github.com/users/coder2020official/followers", "following_url": "https://api.github.com/users/coder2020official/following{/other_user}", "gists_url": "https://api.github.com/users/coder2020official/gists{/gist_id}", "starred_url": "https://api.github.com/users/coder2020official/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/coder2020official/subscriptions", "organizations_url": "https://api.github.com/users/coder2020official/orgs", "repos_url": "https://api.github.com/users/coder2020official/repos", "events_url": "https://api.github.com/users/coder2020official/events{/privacy}", "received_events_url": "https://api.github.com/users/coder2020official/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 4, "created_at": "2022-05-04T11:05:25Z", "updated_at": "2022-08-23T16:16:57Z", "closed_at": "2022-08-23T16:16:57Z", "author_association": "COLLABORATOR", "active_lock_reason": null, "body": "Please answer these questions before submitting your issue. Thanks!\r\nTested 3 different storages: Pickle, Redis, Memory - only asynchronous ones.\r\nRedis storage needs to be improved in order to support concurrency.\r\n\r\n1. What version of pyTelegramBotAPI are you using?\r\n4.5.0\r\n2. What OS are you using?\r\nMacOS\r\n3. What version of python are you using?\r\n4. 3.9.6\r\n", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1530/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1530/timeline", "performed_via_github_app": null, "state_reason": "not_planned"}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1505", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1505/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1505/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1505/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/issues/1505", "id": 1208162380, "node_id": "I_kwDOAkVMUs5IAxhM", "number": 1505, "title": "Send_invoice currency error.", "user": {"login": "captainluzik", "id": 22837036, "node_id": "MDQ6VXNlcjIyODM3MDM2", "avatar_url": "https://avatars.githubusercontent.com/u/22837036?v=4", "gravatar_id": "", "url": "https://api.github.com/users/captainluzik", "html_url": "https://github.com/captainluzik", "followers_url": "https://api.github.com/users/captainluzik/followers", "following_url": "https://api.github.com/users/captainluzik/following{/other_user}", "gists_url": "https://api.github.com/users/captainluzik/gists{/gist_id}", "starred_url": "https://api.github.com/users/captainluzik/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/captainluzik/subscriptions", "organizations_url": "https://api.github.com/users/captainluzik/orgs", "repos_url": "https://api.github.com/users/captainluzik/repos", "events_url": "https://api.github.com/users/captainluzik/events{/privacy}", "received_events_url": "https://api.github.com/users/captainluzik/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": {"login": "Badiboy", "id": 5613421, "node_id": "MDQ6VXNlcjU2MTM0MjE=", "avatar_url": "https://avatars.githubusercontent.com/u/5613421?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Badiboy", "html_url": "https://github.com/Badiboy", "followers_url": "https://api.github.com/users/Badiboy/followers", "following_url": "https://api.github.com/users/Badiboy/following{/other_user}", "gists_url": "https://api.github.com/users/Badiboy/gists{/gist_id}", "starred_url": "https://api.github.com/users/Badiboy/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Badiboy/subscriptions", "organizations_url": "https://api.github.com/users/Badiboy/orgs", "repos_url": "https://api.github.com/users/Badiboy/repos", "events_url": "https://api.github.com/users/Badiboy/events{/privacy}", "received_events_url": "https://api.github.com/users/Badiboy/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "Badiboy", "id": 5613421, "node_id": "MDQ6VXNlcjU2MTM0MjE=", "avatar_url": "https://avatars.githubusercontent.com/u/5613421?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Badiboy", "html_url": "https://github.com/Badiboy", "followers_url": "https://api.github.com/users/Badiboy/followers", "following_url": "https://api.github.com/users/Badiboy/following{/other_user}", "gists_url": "https://api.github.com/users/Badiboy/gists{/gist_id}", "starred_url": "https://api.github.com/users/Badiboy/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Badiboy/subscriptions", "organizations_url": "https://api.github.com/users/Badiboy/orgs", "repos_url": "https://api.github.com/users/Badiboy/repos", "events_url": "https://api.github.com/users/Badiboy/events{/privacy}", "received_events_url": "https://api.github.com/users/Badiboy/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 4, "created_at": "2022-04-19T10:40:48Z", "updated_at": "2022-04-23T13:28:01Z", "closed_at": "2022-04-23T13:28:01Z", "author_association": "NONE", "active_lock_reason": null, "body": "Please answer these questions before submitting your issue. Thanks!\r\n\r\n1. What version of pyTelegramBotAPI are you using?\r\npyTelegramBotAPI==4.4.1\r\n\r\n3. What OS are you using?\r\nWindows 11\r\n4. What version of python are you using?\r\n3.9\r\n\r\nif send invoice from your example code handle this error (with ANY currency from currency list in telegram)\r\n`ERROR - TeleBot: \"A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: CURRENCY_INVALID\"`", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1505/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1505/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1144", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1144/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1144/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1144/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/issues/1144", "id": 868986565, "node_id": "MDU6SXNzdWU4Njg5ODY1NjU=", "number": 1144, "title": "AttributeError: 'NoneType' object has no attribute 'mime_type'", "user": {"login": "kozlovalex", "id": 10797096, "node_id": "MDQ6VXNlcjEwNzk3MDk2", "avatar_url": "https://avatars.githubusercontent.com/u/10797096?v=4", "gravatar_id": "", "url": "https://api.github.com/users/kozlovalex", "html_url": "https://github.com/kozlovalex", "followers_url": "https://api.github.com/users/kozlovalex/followers", "following_url": "https://api.github.com/users/kozlovalex/following{/other_user}", "gists_url": "https://api.github.com/users/kozlovalex/gists{/gist_id}", "starred_url": "https://api.github.com/users/kozlovalex/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/kozlovalex/subscriptions", "organizations_url": "https://api.github.com/users/kozlovalex/orgs", "repos_url": "https://api.github.com/users/kozlovalex/repos", "events_url": "https://api.github.com/users/kozlovalex/events{/privacy}", "received_events_url": "https://api.github.com/users/kozlovalex/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": {"login": "Badiboy", "id": 5613421, "node_id": "MDQ6VXNlcjU2MTM0MjE=", "avatar_url": "https://avatars.githubusercontent.com/u/5613421?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Badiboy", "html_url": "https://github.com/Badiboy", "followers_url": "https://api.github.com/users/Badiboy/followers", "following_url": "https://api.github.com/users/Badiboy/following{/other_user}", "gists_url": "https://api.github.com/users/Badiboy/gists{/gist_id}", "starred_url": "https://api.github.com/users/Badiboy/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Badiboy/subscriptions", "organizations_url": "https://api.github.com/users/Badiboy/orgs", "repos_url": "https://api.github.com/users/Badiboy/repos", "events_url": "https://api.github.com/users/Badiboy/events{/privacy}", "received_events_url": "https://api.github.com/users/Badiboy/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "Badiboy", "id": 5613421, "node_id": "MDQ6VXNlcjU2MTM0MjE=", "avatar_url": "https://avatars.githubusercontent.com/u/5613421?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Badiboy", "html_url": "https://github.com/Badiboy", "followers_url": "https://api.github.com/users/Badiboy/followers", "following_url": "https://api.github.com/users/Badiboy/following{/other_user}", "gists_url": "https://api.github.com/users/Badiboy/gists{/gist_id}", "starred_url": "https://api.github.com/users/Badiboy/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Badiboy/subscriptions", "organizations_url": "https://api.github.com/users/Badiboy/orgs", "repos_url": "https://api.github.com/users/Badiboy/repos", "events_url": "https://api.github.com/users/Badiboy/events{/privacy}", "received_events_url": "https://api.github.com/users/Badiboy/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 2, "created_at": "2021-04-27T15:37:38Z", "updated_at": "2021-05-25T20:57:25Z", "closed_at": "2021-05-25T20:57:25Z", "author_association": "NONE", "active_lock_reason": null, "body": "some examples cause exceptions when processing simple text messages\r\n\r\n```\r\n@bot.message_handler(func=lambda message: message.document.mime_type == 'text/plain', content_types=['document'])\r\ndef handle_text_doc(message):\r\n\tpass\r\n```\r\nraises an exception\r\n```\r\n@bot.message_handler(func=lambda message: message.document.mime_type == 'text/plain', content_types=['document'])\r\nAttributeError: 'NoneType' object has no attribute 'mime_type'\r\n```\r\nand\r\n\r\n```\r\ndef test_message(message):\r\n\treturn message.document.mime_type == 'text/plain'\r\n\r\n@bot.message_handler(func=test_message, content_types=['document'])\r\ndef handle_text_doc(message):\r\n\tpass\r\n```\r\nraises an exception\r\n```\r\nreturn message.document.mime_type == 'text/plain'\r\nAttributeError: 'NoneType' object has no attribute 'mime_type'\r\n```\r\n\r\n\r\npyTelegramBotAPI==3.7.7\r\nLinux Mint 20.1\r\nPython 3.8.5", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1144/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1144/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1068", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1068/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1068/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1068/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/issues/1068", "id": 783492526, "node_id": "MDU6SXNzdWU3ODM0OTI1MjY=", "number": 1068, "title": "Which command should I use to temporarily mute a user?", "user": {"login": "bercedev", "id": 75228263, "node_id": "MDQ6VXNlcjc1MjI4MjYz", "avatar_url": "https://avatars.githubusercontent.com/u/75228263?v=4", "gravatar_id": "", "url": "https://api.github.com/users/bercedev", "html_url": "https://github.com/bercedev", "followers_url": "https://api.github.com/users/bercedev/followers", "following_url": "https://api.github.com/users/bercedev/following{/other_user}", "gists_url": "https://api.github.com/users/bercedev/gists{/gist_id}", "starred_url": "https://api.github.com/users/bercedev/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/bercedev/subscriptions", "organizations_url": "https://api.github.com/users/bercedev/orgs", "repos_url": "https://api.github.com/users/bercedev/repos", "events_url": "https://api.github.com/users/bercedev/events{/privacy}", "received_events_url": "https://api.github.com/users/bercedev/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 8, "created_at": "2021-01-11T15:56:38Z", "updated_at": "2021-01-17T22:08:07Z", "closed_at": "2021-01-17T22:08:07Z", "author_association": "NONE", "active_lock_reason": null, "body": "Please answer these questions before submitting your issue. Thanks!\r\n\r\n1. What version of pyTelegramBotAPI are you using?\r\n\r\n2. What OS are you using?\r\n\r\n3. What version of python are you using?\r\n", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1068/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1068/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1058", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1058/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1058/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1058/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/issues/1058", "id": 777073016, "node_id": "MDU6SXNzdWU3NzcwNzMwMTY=", "number": 1058, "title": "Bot does not recover properly when using infinity_polling", "user": {"login": "ModischFabrications", "id": 25404728, "node_id": "MDQ6VXNlcjI1NDA0NzI4", "avatar_url": "https://avatars.githubusercontent.com/u/25404728?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ModischFabrications", "html_url": "https://github.com/ModischFabrications", "followers_url": "https://api.github.com/users/ModischFabrications/followers", "following_url": "https://api.github.com/users/ModischFabrications/following{/other_user}", "gists_url": "https://api.github.com/users/ModischFabrications/gists{/gist_id}", "starred_url": "https://api.github.com/users/ModischFabrications/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ModischFabrications/subscriptions", "organizations_url": "https://api.github.com/users/ModischFabrications/orgs", "repos_url": "https://api.github.com/users/ModischFabrications/repos", "events_url": "https://api.github.com/users/ModischFabrications/events{/privacy}", "received_events_url": "https://api.github.com/users/ModischFabrications/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 30, "created_at": "2020-12-31T16:05:37Z", "updated_at": "2021-01-17T22:01:30Z", "closed_at": "2021-01-17T22:01:30Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "1. What version of pyTelegramBotAPI are you using? 3.7.4\r\n\r\n2. What OS are you using? Raspbian\r\n\r\n3. What version of python are you using? 3.6.9\r\n\r\n-----------------------\r\n\r\nTesting out `bot.infinity_polling()` as recommended in #1057 I noticed a bug in the recovery from exceptions:\r\n\r\nIt seems like the bot does not recover completely from a collision from another bot instance. It crashes and restarts successfully, which is nice, but it seems to get stuck in a restart loop every 3s (sleep time on recovery). I would guess there is an implicit state that carries over the restart that still contains the cancel instruction, but I haven't found anything obvious. \r\n\r\nThis bug can be bypassed by not starting another instance with the same token, but I assume that the same bug will also strike with other exceptions, unrelated to this cause. \r\n\r\nReproduction: \r\n1. Start instance 1 with `bot.infinity_polling()` and logging.INFO\r\n2. Start another instance to provoke a collision\r\n3. stop second bot to allow instance 1 to run\r\n4. -> instance 1 has crashed and is stuck in restart loop afterwards\r\n\r\nlog instance 1: \r\n```\r\n2020-12-31 16:03:07,705 (__init__.py:460 MainThread) INFO - TeleBot: \"Started polling.\"\r\n2020-12-31 16:19:07,961 (__init__.py:489 MainThread) ERROR - TeleBot: \"A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"\r\n2020-12-31 16:19:07,961 (__init__.py:496 MainThread) INFO - TeleBot: \"Waiting for 0.25 seconds until retry\"\r\n2020-12-31 16:19:11,546 (__init__.py:489 MainThread) ERROR - TeleBot: \"A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"\r\n2020-12-31 16:19:11,546 (__init__.py:496 MainThread) INFO - TeleBot: \"Waiting for 0.5 seconds until retry\"\r\n2020-12-31 16:42:57,901 (__init__.py:460 MainThread) INFO - TeleBot: \"Started polling.\"\r\n2020-12-31 16:43:00,905 (__init__.py:460 MainThread) INFO - TeleBot: \"Started polling.\"\r\n2020-12-31 16:43:03,908 (__init__.py:460 MainThread) INFO - TeleBot: \"Started polling.\"\r\n2020-12-31 16:43:06,914 (__init__.py:460 MainThread) INFO - TeleBot: \"Started polling.\"\r\n2020-12-31 16:43:09,920 (__init__.py:460 MainThread) INFO - TeleBot: \"Started polling.\"\r\n```\r\n\r\nlog instance 2:\r\n```\r\n2020-12-31 16:19:07,872 (__init__.py:460 MainThread) INFO - TeleBot: \"Started polling.\"\r\n2020-12-31 16:19:11,256 (__init__.py:489 MainThread) ERROR - TeleBot: \"A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"\r\n2020-12-31 16:19:11,256 (__init__.py:496 MainThread) INFO - TeleBot: \"Waiting for 0.25 seconds until retry\"\r\n\r\nProcess finished with exit code -1\r\n```\r\n\r\nPS: Happy new year and thanks for the fast responses!\r\n", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1058/reactions", "total_count": 1, "+1": 1, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1058/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1010", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1010/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1010/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1010/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/issues/1010", "id": 738203534, "node_id": "MDU6SXNzdWU3MzgyMDM1MzQ=", "number": 1010, "title": "Telegram API timeout parameter for long polling on getUpdates not used?", "user": {"login": "VersilPerihelion", "id": 16778116, "node_id": "MDQ6VXNlcjE2Nzc4MTE2", "avatar_url": "https://avatars.githubusercontent.com/u/16778116?v=4", "gravatar_id": "", "url": "https://api.github.com/users/VersilPerihelion", "html_url": "https://github.com/VersilPerihelion", "followers_url": "https://api.github.com/users/VersilPerihelion/followers", "following_url": "https://api.github.com/users/VersilPerihelion/following{/other_user}", "gists_url": "https://api.github.com/users/VersilPerihelion/gists{/gist_id}", "starred_url": "https://api.github.com/users/VersilPerihelion/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/VersilPerihelion/subscriptions", "organizations_url": "https://api.github.com/users/VersilPerihelion/orgs", "repos_url": "https://api.github.com/users/VersilPerihelion/repos", "events_url": "https://api.github.com/users/VersilPerihelion/events{/privacy}", "received_events_url": "https://api.github.com/users/VersilPerihelion/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2020-11-07T08:59:25Z", "updated_at": "2020-11-08T09:56:36Z", "closed_at": "2020-11-08T09:55:06Z", "author_association": "NONE", "active_lock_reason": null, "body": "Please answer these questions before submitting your issue. Thanks!\r\n\r\n1. What version of pyTelegramBotAPI are you using?\r\n3.7.3\r\n\r\n2. What OS are you using?\r\nUbuntu 20.04.1\r\n\r\n3. What version of python are you using?\r\n3.8.5\r\n---\r\nIs it a deliberate change that getUpdates requests made by the bots no longer use Telegram API's timeout parameter for long polling?\r\nIn apihelper, in `_make_request`:\r\n```python\r\n    if params:\r\n        if 'timeout' in params:\r\n            read_timeout = params.pop('timeout') + 10\r\n        if 'connect-timeout' in params:\r\n            connect_timeout = params.pop('connect-timeout') + 10\r\n```\r\n`timeout` is removed from query string params,\r\n```python\r\n        result = _get_req_session().request(\r\n            method, request_url, params=params, files=files,\r\n            timeout=(connect_timeout, read_timeout), proxies=proxy)\r\n```\r\nand not restored in any way afterwards, calling getUpdates without it.\r\n\r\nAnd as expected from the timeout parameter not sent to the API and the API docs saying it defaults to 0, I'm seeing empty responses arriving immediately, rather than only with no updates after the desired timeout.\r\n\r\nHave not found any prior issue mentioning it, and traced the change to May, to PR #848 where accessing `timeout` from the `params` dict was replaced with calling `.pop` on it.", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1010/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/1010/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/314", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/314/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/314/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/314/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/issues/314", "id": 217083354, "node_id": "MDU6SXNzdWUyMTcwODMzNTQ=", "number": 314, "title": "get webhook info exception", "user": {"login": "globax89", "id": 21222809, "node_id": "MDQ6VXNlcjIxMjIyODA5", "avatar_url": "https://avatars.githubusercontent.com/u/21222809?v=4", "gravatar_id": "", "url": "https://api.github.com/users/globax89", "html_url": "https://github.com/globax89", "followers_url": "https://api.github.com/users/globax89/followers", "following_url": "https://api.github.com/users/globax89/following{/other_user}", "gists_url": "https://api.github.com/users/globax89/gists{/gist_id}", "starred_url": "https://api.github.com/users/globax89/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/globax89/subscriptions", "organizations_url": "https://api.github.com/users/globax89/orgs", "repos_url": "https://api.github.com/users/globax89/repos", "events_url": "https://api.github.com/users/globax89/events{/privacy}", "received_events_url": "https://api.github.com/users/globax89/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2017-03-26T19:45:38Z", "updated_at": "2017-05-30T09:18:26Z", "closed_at": "2017-05-30T09:18:26Z", "author_association": "NONE", "active_lock_reason": null, "body": "Please answer these questions before submitting your issue. Thanks!\r\n\r\n    What version of pyTelegramBotAPI are you using?\r\n\r\npyTelegramBotAPI==2.3.1\r\n\r\n    What OS are you using?\r\n\r\nLinux 3.10.0-514.6.1.el7.x86_64 x86_64 GNU/Linux\r\n\r\n    What version of python are you using?\r\n\r\nPython 3.5.2\r\n\r\nGood time, want to use the method get_webhook_info(), but to get the exception:\r\n\r\n  File \"/usr/local/lib/python3.5/site-packages/telebot/types.py\", line 151, in de_json\r\n    return cls(url, has_custom_certificate, pending_update_count, last_error_date, last_error_message, max_connections, allowed_updates)\r\nUnboundLocalError: local variable 'allowed_updates' referenced before assignment\r\n\r\nAs far as I understand, the problem is that allowed_updates and max_connection variables not initialized with a value of None.\r\n\r\n", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/314/reactions", "total_count": 2, "+1": 2, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/314/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/164", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/164/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/164/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/164/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/issues/164", "id": 155171806, "node_id": "MDU6SXNzdWUxNTUxNzE4MDY=", "number": 164, "title": "cannot add bot buttons with emoji as unicode...", "user": {"login": "Baylung", "id": 18363588, "node_id": "MDQ6VXNlcjE4MzYzNTg4", "avatar_url": "https://avatars.githubusercontent.com/u/18363588?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Baylung", "html_url": "https://github.com/Baylung", "followers_url": "https://api.github.com/users/Baylung/followers", "following_url": "https://api.github.com/users/Baylung/following{/other_user}", "gists_url": "https://api.github.com/users/Baylung/gists{/gist_id}", "starred_url": "https://api.github.com/users/Baylung/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Baylung/subscriptions", "organizations_url": "https://api.github.com/users/Baylung/orgs", "repos_url": "https://api.github.com/users/Baylung/repos", "events_url": "https://api.github.com/users/Baylung/events{/privacy}", "received_events_url": "https://api.github.com/users/Baylung/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2016-05-17T03:53:36Z", "updated_at": "2019-05-30T16:53:17Z", "closed_at": "2016-05-19T08:03:21Z", "author_association": "NONE", "active_lock_reason": null, "body": "Before upgrading to pyTelegramBotAPI 2.1.1 my keyboard with emoji-buttons was working good:\n\n```\nall_lang_markup = types.ReplyKeyboardMarkup( resize_keyboard=True )\nall_lang_markup.add( u'\\U0001F1EC', u'\\U0001F1F7')   # English and Russian Emoji Flags\n\n```\n\nAfter upgrating to pyTelegramBotAPI 2.1.1 (pip install pyTelegramBotAPI -U) bot cannot be launched with and followin error raised:\n\n```\nFile \"/usr/local/lib/python2.7/dist-packages/telebot/types.py\", line 559, in add\n    row.append(button.to_dic())\nAttributeError: 'unicode' object has no attribute 'to_dic'\n```\n\nPlease check..\n\nHow can i add keyboard button containing Emoji icons in  pyTelegramBotAPI 2.1.1 ?\n\nPS. Thank you for pyTelegramBotAPI - the best library interface to Telegram bot API ! \n", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/164/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/164/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/96", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/96/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/96/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/96/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/issues/96", "id": 115949284, "node_id": "MDU6SXNzdWUxMTU5NDkyODQ=", "number": 96, "title": "JSON error when sending msg to channel", "user": {"login": "TTimoNN", "id": 15086872, "node_id": "MDQ6VXNlcjE1MDg2ODcy", "avatar_url": "https://avatars.githubusercontent.com/u/15086872?v=4", "gravatar_id": "", "url": "https://api.github.com/users/TTimoNN", "html_url": "https://github.com/TTimoNN", "followers_url": "https://api.github.com/users/TTimoNN/followers", "following_url": "https://api.github.com/users/TTimoNN/following{/other_user}", "gists_url": "https://api.github.com/users/TTimoNN/gists{/gist_id}", "starred_url": "https://api.github.com/users/TTimoNN/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/TTimoNN/subscriptions", "organizations_url": "https://api.github.com/users/TTimoNN/orgs", "repos_url": "https://api.github.com/users/TTimoNN/repos", "events_url": "https://api.github.com/users/TTimoNN/events{/privacy}", "received_events_url": "https://api.github.com/users/TTimoNN/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 6, "created_at": "2015-11-09T19:37:48Z", "updated_at": "2015-11-12T10:37:11Z", "closed_at": "2015-11-12T10:37:11Z", "author_association": "NONE", "active_lock_reason": null, "body": "error:\n\"\"\"\nException in thread WorkerThread3:\nTraceback (most recent call last):\n  File \"/usr/local/lib/python2.7/threading.py\", line 810, in **bootstrap_inner\n    self.run()\n  File \"/usr/local/lib/python2.7/site-packages/telebot/util.py\", line 30, in run\n    task(_args, *_kwargs)\n  File \"tg3.py\", line 25, in listener\n    tb.send_message('@timontest', \"chicken\")\n  File \"/usr/local/lib/python2.7/site-packages/telebot/__init**.py\", line 204, in send_message\n    reply_markup, parse_mode))\n  File \"/usr/local/lib/python2.7/site-packages/telebot/types.py\", line 132, in de_json\n    from_user = User.de_json(obj['from'])\nKeyError: 'from'\n\"\"\"\ncode: https://gist.github.com/anonymous/692ecda96dcc9d5557f7\n", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/96/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/96/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/92", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/92/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/92/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/92/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/issues/92", "id": 113238476, "node_id": "MDU6SXNzdWUxMTMyMzg0NzY=", "number": 92, "title": "register_next_step_handler", "user": {"login": "azg1966", "id": 2987166, "node_id": "MDQ6VXNlcjI5ODcxNjY=", "avatar_url": "https://avatars.githubusercontent.com/u/2987166?v=4", "gravatar_id": "", "url": "https://api.github.com/users/azg1966", "html_url": "https://github.com/azg1966", "followers_url": "https://api.github.com/users/azg1966/followers", "following_url": "https://api.github.com/users/azg1966/following{/other_user}", "gists_url": "https://api.github.com/users/azg1966/gists{/gist_id}", "starred_url": "https://api.github.com/users/azg1966/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/azg1966/subscriptions", "organizations_url": "https://api.github.com/users/azg1966/orgs", "repos_url": "https://api.github.com/users/azg1966/repos", "events_url": "https://api.github.com/users/azg1966/events{/privacy}", "received_events_url": "https://api.github.com/users/azg1966/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2015-10-25T17:28:09Z", "updated_at": "2015-10-26T19:12:51Z", "closed_at": "2015-10-26T19:12:51Z", "author_association": "NONE", "active_lock_reason": null, "body": "Then bot created with \"threaded=False\", process_name_step called right after \"bot.register_next_step_handler(msg, process_age_step)\" , without waiting new message.\n\n``` python\n@bot.message_handler(commands=['help', 'start'])\ndef send_welcome(message):\n    msg = bot.reply_to(message, \"\"\"\\\nHi there, I am Example bot.\nWhat's your name?\n\"\"\")\n    bot.register_next_step_handler(msg, process_name_step)\n\ndef process_name_step(message):\n    try:\n        chat_id = message.chat.id\n        name = message.text\n        user = User(name)\n        user_dict[chat_id] = user\n        msg = bot.reply_to(message, 'How old are you?')\n        bot.register_next_step_handler(msg, process_age_step)\n    except Exception as e:\n        bot.reply_to(message, 'oooops')\n```\n", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/92/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/92/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/83", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/83/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/83/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/83/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/issues/83", "id": 110086140, "node_id": "MDU6SXNzdWUxMTAwODYxNDA=", "number": 83, "title": "Getting Unicode error", "user": {"login": "nd7141", "id": 4607709, "node_id": "MDQ6VXNlcjQ2MDc3MDk=", "avatar_url": "https://avatars.githubusercontent.com/u/4607709?v=4", "gravatar_id": "", "url": "https://api.github.com/users/nd7141", "html_url": "https://github.com/nd7141", "followers_url": "https://api.github.com/users/nd7141/followers", "following_url": "https://api.github.com/users/nd7141/following{/other_user}", "gists_url": "https://api.github.com/users/nd7141/gists{/gist_id}", "starred_url": "https://api.github.com/users/nd7141/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/nd7141/subscriptions", "organizations_url": "https://api.github.com/users/nd7141/orgs", "repos_url": "https://api.github.com/users/nd7141/repos", "events_url": "https://api.github.com/users/nd7141/events{/privacy}", "received_events_url": "https://api.github.com/users/nd7141/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2015-10-06T19:50:19Z", "updated_at": "2015-10-06T20:42:54Z", "closed_at": "2015-10-06T20:42:54Z", "author_association": "NONE", "active_lock_reason": null, "body": "I have the following error:\n\nTraceback (most recent call last):\n    updates = telebot.apihelper.get_updates(self.token, offset=(self.last_update_id + 1), timeout=20)\n  File \"/usr/local/lib/python2.7/dist-packages/telebot/apihelper.py\", line 129, in get_updates\n    return _make_request(token, method_url, params=payload)\n  File \"/usr/local/lib/python2.7/dist-packages/telebot/apihelper.py\", line 28, in _make_request\n    return _check_result(method_name, result)['result']\n  File \"/usr/local/lib/python2.7/dist-packages/telebot/apihelper.py\", line 53, in _check_result\n    .format(result.text)\nUnicodeEncodeError: 'ascii' codec can't encode character u'\\u2014' in position 4530: ordinal not in range(128)\n", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/83/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/83/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/79", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/79/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/79/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/79/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/79", "id": 109082273, "node_id": "MDExOlB1bGxSZXF1ZXN0NDYzOTg2MDA=", "number": 79, "title": "fix race-condition for register_for_reply", "user": {"login": "huiyiqun", "id": 3468160, "node_id": "MDQ6VXNlcjM0NjgxNjA=", "avatar_url": "https://avatars.githubusercontent.com/u/3468160?v=4", "gravatar_id": "", "url": "https://api.github.com/users/huiyiqun", "html_url": "https://github.com/huiyiqun", "followers_url": "https://api.github.com/users/huiyiqun/followers", "following_url": "https://api.github.com/users/huiyiqun/following{/other_user}", "gists_url": "https://api.github.com/users/huiyiqun/gists{/gist_id}", "starred_url": "https://api.github.com/users/huiyiqun/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/huiyiqun/subscriptions", "organizations_url": "https://api.github.com/users/huiyiqun/orgs", "repos_url": "https://api.github.com/users/huiyiqun/repos", "events_url": "https://api.github.com/users/huiyiqun/events{/privacy}", "received_events_url": "https://api.github.com/users/huiyiqun/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 5, "created_at": "2015-09-30T13:04:53Z", "updated_at": "2015-09-30T14:50:08Z", "closed_at": "2015-09-30T14:50:08Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "draft": false, "pull_request": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/pulls/79", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/79", "diff_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/79.diff", "patch_url": "https://github.com/eternnoir/pyTelegramBotAPI/pull/79.patch", "merged_at": "2015-09-30T14:50:08Z"}, "body": "Here is a race-condition in current code.\n\nIf `command A` registers `for_reply a`, and `for_reply a` registers `for_reply b`, then `for_reply b` will be wrongly deleted from the list and never be triggered.\n\nBecause before `for_reply a` is called, `for_reply a` is located in the first position of `message_subscribers_callbacks`, but after `for_reply a` accomplishes, when `for_reply b` is registered, `for_reply b` is located in the first place and `for_reply a` is located in the second one.\nThe `for_reply b` is wrongly deleted and `for_reply a` is left.\n\nThere are two methods to resolve this problem:\n1. Reserve the `message_subscribers_callbacks` and the `message_subscribers_messages`. As a result, the position of `for_reply a` will not change during the process. But considering that when there is too many `for_replys`, the oldest will be removed, the similar problem will happen.\n2. Search the index of `for_reply` before deleting it. It's ugly somewhat but it works.\n\nWhat's more, I'm not sure if there will some other race-conditions cansed by multi-thread, such as `message_subscribers_messages` correspond with an unmeet `message_subscribers_callbacks`.\nI add a lock to keep the two list matching. If it's not needed, I will remove it.\n", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/79/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/79/timeline", "performed_via_github_app": null, "state_reason": null}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/78", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/78/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/78/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/78/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/issues/78", "id": 108602515, "node_id": "MDU6SXNzdWUxMDg2MDI1MTU=", "number": 78, "title": "Unhandled exceptions in the polling Thread causes bot to stop working but the process doesn't die.", "user": {"login": "skgsergio", "id": 186349, "node_id": "MDQ6VXNlcjE4NjM0OQ==", "avatar_url": "https://avatars.githubusercontent.com/u/186349?v=4", "gravatar_id": "", "url": "https://api.github.com/users/skgsergio", "html_url": "https://github.com/skgsergio", "followers_url": "https://api.github.com/users/skgsergio/followers", "following_url": "https://api.github.com/users/skgsergio/following{/other_user}", "gists_url": "https://api.github.com/users/skgsergio/gists{/gist_id}", "starred_url": "https://api.github.com/users/skgsergio/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/skgsergio/subscriptions", "organizations_url": "https://api.github.com/users/skgsergio/orgs", "repos_url": "https://api.github.com/users/skgsergio/repos", "events_url": "https://api.github.com/users/skgsergio/events{/privacy}", "received_events_url": "https://api.github.com/users/skgsergio/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}, {"id": 229170313, "node_id": "MDU6TGFiZWwyMjkxNzAzMTM=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/enhancement", "name": "enhancement", "color": "84b6eb", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 12, "created_at": "2015-09-28T07:31:06Z", "updated_at": "2015-10-06T20:39:41Z", "closed_at": "2015-10-06T20:39:41Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "If an Exception occurs in the polling _Thread_, then the bot stays running but not receiving more updates, seems like the polling thread dies but doesn't exit the process.\n\nMore Info in https://github.com/eternnoir/pyTelegramBotAPI/issues/78#issuecomment-144653036\n\n```\nException in thread Thread-1:\nTraceback (most recent call last):\n  File \"/usr/lib/python2.7/threading.py\", line 810, in __bootstrap_inner\n    self.run()\n  File \"/usr/lib/python2.7/threading.py\", line 763, in run\n    self.__target(*self.__args, **self.__kwargs)\n  File \"/home/sergio/.local/lib/python2.7/site-packages/telebot/__init__.py\", line 145, in __polling\n    self.get_update()\n  File \"/home/sergio/.local/lib/python2.7/site-packages/telebot/__init__.py\", line 87, in get_update\n    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=3)\n  File \"/home/sergio/.local/lib/python2.7/site-packages/telebot/__init__.py\", line 75, in get_updates\n    json_updates = apihelper.get_updates(self.token, offset, limit, timeout)\n  File \"/home/sergio/.local/lib/python2.7/site-packages/telebot/apihelper.py\", line 117, in get_updates\n    return _make_request(token, method_url, params=payload)\n  File \"/home/sergio/.local/lib/python2.7/site-packages/telebot/apihelper.py\", line 26, in _make_request\n    result = requests.request(method, request_url, params=params, files=files)\n  File \"/usr/lib/python2.7/dist-packages/requests/api.py\", line 49, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/usr/lib/python2.7/dist-packages/requests/sessions.py\", line 457, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/usr/lib/python2.7/dist-packages/requests/sessions.py\", line 569, in send\n    r = adapter.send(request, **kwargs)\n  File \"/usr/lib/python2.7/dist-packages/requests/adapters.py\", line 420, in send\n    raise SSLError(e, request=request)\nSSLError: EOF occurred in violation of protocol (_ssl.c:581)\n```\n", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/78/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/78/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/48", "repository_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI", "labels_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/48/labels{/name}", "comments_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/48/comments", "events_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/48/events", "html_url": "https://github.com/eternnoir/pyTelegramBotAPI/issues/48", "id": 96482033, "node_id": "MDU6SXNzdWU5NjQ4MjAzMw==", "number": 48, "title": "[BUG]regexp handler fail", "user": {"login": "eternnoir", "id": 1109538, "node_id": "MDQ6VXNlcjExMDk1Mzg=", "avatar_url": "https://avatars.githubusercontent.com/u/1109538?v=4", "gravatar_id": "", "url": "https://api.github.com/users/eternnoir", "html_url": "https://github.com/eternnoir", "followers_url": "https://api.github.com/users/eternnoir/followers", "following_url": "https://api.github.com/users/eternnoir/following{/other_user}", "gists_url": "https://api.github.com/users/eternnoir/gists{/gist_id}", "starred_url": "https://api.github.com/users/eternnoir/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/eternnoir/subscriptions", "organizations_url": "https://api.github.com/users/eternnoir/orgs", "repos_url": "https://api.github.com/users/eternnoir/repos", "events_url": "https://api.github.com/users/eternnoir/events{/privacy}", "received_events_url": "https://api.github.com/users/eternnoir/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 229170311, "node_id": "MDU6TGFiZWwyMjkxNzAzMTE=", "url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2015-07-22T06:00:46Z", "updated_at": "2015-07-22T06:49:22Z", "closed_at": "2015-07-22T06:49:22Z", "author_association": "OWNER", "active_lock_reason": null, "body": "regexp handler not work.\n", "reactions": {"url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/48/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/eternnoir/pyTelegramBotAPI/issues/48/timeline", "performed_via_github_app": null, "state_reason": "completed"}]