[{"url": "https://api.github.com/repos/inveniosoftware/invenio/issues/4083", "repository_url": "https://api.github.com/repos/inveniosoftware/invenio", "labels_url": "https://api.github.com/repos/inveniosoftware/invenio/issues/4083/labels{/name}", "comments_url": "https://api.github.com/repos/inveniosoftware/invenio/issues/4083/comments", "events_url": "https://api.github.com/repos/inveniosoftware/invenio/issues/4083/events", "html_url": "https://github.com/inveniosoftware/invenio/issues/4083", "id": 811163151, "node_id": "MDU6SXNzdWU4MTExNjMxNTE=", "number": 4083, "title": "scripts/bootstrap fails at installing react-overridable", "user": {"login": "davekch", "id": 35708136, "node_id": "MDQ6VXNlcjM1NzA4MTM2", "avatar_url": "https://avatars.githubusercontent.com/u/35708136?v=4", "gravatar_id": "", "url": "https://api.github.com/users/davekch", "html_url": "https://github.com/davekch", "followers_url": "https://api.github.com/users/davekch/followers", "following_url": "https://api.github.com/users/davekch/following{/other_user}", "gists_url": "https://api.github.com/users/davekch/gists{/gist_id}", "starred_url": "https://api.github.com/users/davekch/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/davekch/subscriptions", "organizations_url": "https://api.github.com/users/davekch/orgs", "repos_url": "https://api.github.com/users/davekch/repos", "events_url": "https://api.github.com/users/davekch/events{/privacy}", "received_events_url": "https://api.github.com/users/davekch/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 4031214816, "node_id": "MDU6TGFiZWw0MDMxMjE0ODE2", "url": "https://api.github.com/repos/inveniosoftware/invenio/labels/bug", "name": "bug", "color": "d73a4a", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2021-02-18T14:43:44Z", "updated_at": "2021-02-21T15:16:52Z", "closed_at": "2021-02-21T15:16:51Z", "author_association": "NONE", "active_lock_reason": null, "body": "Package version (if known): 3.4.0\r\n\r\n## Describe the bug\r\nRunning `./scripts/bootstrap` as described in the [tutorial](https://invenio.readthedocs.io/en/latest/getting-started/quickstart/installation.html) fails with the following error:\r\n```\r\nnpm ERR! code ERESOLVE                                                                                                                                                                                          \r\nnpm ERR! ERESOLVE unable to resolve dependency tree                                                                                                                                                             \r\nnpm ERR!                                                                                                                                                                                                        \r\nnpm ERR! While resolving: invenio-assets@1.0.0                                                                                                                                                                  \r\nnpm ERR! Found: react-overridable@0.0.2                                                                                                                                                                         \r\nnpm ERR! node_modules/react-overridable                                                                                                                                                                         \r\nnpm ERR!   react-overridable@\"^0.0.2\" from the root project                                                                                                                                                     \r\nnpm ERR!                                                                                                                                                                                                        \r\nnpm ERR! Could not resolve dependency:                                                                                                                                                                          \r\nnpm ERR! peer react-overridable@\"^0.0.3\" from react-searchkit@1.0.0-alpha.13                                                                                                                                    \r\nnpm ERR! node_modules/react-searchkit                                                                                                                                                                           \r\nnpm ERR!   react-searchkit@\"^1.0.0-alpha.12\" from the root project                                                                                                                                              \r\nnpm ERR!                                                                                                                                                                                                        \r\nnpm ERR! Fix the upstream dependency conflict, or retry                                                                                                                                                         \r\nnpm ERR! this command with --force, or --legacy-peer-deps                                                                                                                                                       \r\nnpm ERR! to accept an incorrect (and potentially broken) dependency resolution.                                                                                                                                 \r\nnpm ERR!                                                                                                                                                                                                        \r\nnpm ERR! See /home/xxx/.npm/eresolve-report.txt for a full report.                                                                                                                                         \r\n                                                                                                                                                                                                                \r\nnpm ERR! A complete log of this run can be found in:                                                                                                                                                            \r\nnpm ERR!     /home/xxx/.npm/_logs/2021-02-18T14_22_16_749Z-debug.log                                                                                                                                       \r\nTraceback (most recent call last):                                                                                                                                                                              \r\n  File \"/home/xxx/venv/bin/invenio\", line 8, in <module>                                                                                                                                                   \r\n    sys.exit(cli())                                                                                                                                                                                             \r\n  File \"/home/xxx/venv/lib/python3.8/site-packages/click/core.py\", line 829, in __call__                                                                                                                   \r\n    return self.main(*args, **kwargs)                                                                                                                                                                           \r\n  File \"/home/xxx/venv/lib/python3.8/site-packages/flask/cli.py\", line 586, in main                                                                                                                        \r\n    return super(FlaskGroup, self).main(*args, **kwargs)                                                                                                                                                        \r\n  File \"/home/xxx/venv/lib/python3.8/site-packages/click/core.py\", line 782, in main                                                                                                                       \r\n    rv = self.invoke(ctx)                                                                                                                                                                                       \r\n  File \"/home/xxx/venv/lib/python3.8/site-packages/click/core.py\", line 1259, in invoke                                                                                                                    \r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                                                                                                     \r\n  File \"/home/xxx/venv/lib/python3.8/site-packages/click/core.py\", line 1289, in invoke                                                                                                                    \r\n    rv.append(sub_ctx.command.invoke(sub_ctx))                                                                                                                                                                  \r\n  File \"/home/xxx/venv/lib/python3.8/site-packages/click/core.py\", line 1066, in invoke                                                                                                                    \r\n    return ctx.invoke(self.callback, **ctx.params)\r\n  File \"/home/xxx/venv/lib/python3.8/site-packages/click/core.py\", line 610, in invoke\r\n    return callback(*args, **kwargs)\r\n  File \"/home/xxx/venv/lib/python3.8/site-packages/click/decorators.py\", line 21, in new_func\r\n    return f(get_current_context(), *args, **kwargs) \r\n  File \"/home/xxx/venv/lib/python3.8/site-packages/flask/cli.py\", line 426, in decorator\r\n    return __ctx.invoke(f, *args, **kwargs)\r\n  File \"/home/xxx/venv/lib/python3.8/site-packages/click/core.py\", line 610, in invoke\r\n    return callback(*args, **kwargs)\r\n  File \"/home/xxx/venv/lib/python3.8/site-packages/flask_webpackext/cli.py\", line 72, in buildall\r\n    current_webpack.project.buildall()\r\n  File \"/home/xxx/venv/lib/python3.8/site-packages/pywebpack/project.py\", line 141, in buildall\r\n    super(WebpackTemplateProject, self).buildall()\r\n  File \"/home/xxx/venv/lib/python3.8/site-packages/pywebpack/project.py\", line 69, in buildall\r\n    self.install()\r\n  File \"/home/xxx/venv/lib/python3.8/site-packages/pywebpack/helpers.py\", line 48, in inner\r\n    raise RuntimeError(\"Process exited with code {}\".format(exit_code))\r\nRuntimeError: Process exited with code 1\r\n```\r\n\r\n## Steps to Reproduce\r\n1. install nodejs and npm (running Ubuntu 20): `curl -fsSL https://deb.nodesource.com/setup_15.x | sudo -E bash - && sudo apt install -y nodejs`\r\n2. `node --version`  v15.8.0, `npm --version` 7.5.4\r\n3. Follow the steps in the tutorial\r\n4. run `./scripts/bootstrap`\r\n\r\n## Expected behavior\r\nThe script finishes without errors\r\n\r\n\r\nPlease let me know if this is actually an issue with react-overridable or npm rather than invenio's bootstrap script.", "reactions": {"url": "https://api.github.com/repos/inveniosoftware/invenio/issues/4083/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/inveniosoftware/invenio/issues/4083/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/inveniosoftware/invenio/issues/4082", "repository_url": "https://api.github.com/repos/inveniosoftware/invenio", "labels_url": "https://api.github.com/repos/inveniosoftware/invenio/issues/4082/labels{/name}", "comments_url": "https://api.github.com/repos/inveniosoftware/invenio/issues/4082/comments", "events_url": "https://api.github.com/repos/inveniosoftware/invenio/issues/4082/events", "html_url": "https://github.com/inveniosoftware/invenio/issues/4082", "id": 782094638, "node_id": "MDU6SXNzdWU3ODIwOTQ2Mzg=", "number": 4082, "title": "ELIFECYCLE error code", "user": {"login": "espenfl", "id": 16185242, "node_id": "MDQ6VXNlcjE2MTg1MjQy", "avatar_url": "https://avatars.githubusercontent.com/u/16185242?v=4", "gravatar_id": "", "url": "https://api.github.com/users/espenfl", "html_url": "https://github.com/espenfl", "followers_url": "https://api.github.com/users/espenfl/followers", "following_url": "https://api.github.com/users/espenfl/following{/other_user}", "gists_url": "https://api.github.com/users/espenfl/gists{/gist_id}", "starred_url": "https://api.github.com/users/espenfl/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/espenfl/subscriptions", "organizations_url": "https://api.github.com/users/espenfl/orgs", "repos_url": "https://api.github.com/users/espenfl/repos", "events_url": "https://api.github.com/users/espenfl/events{/privacy}", "received_events_url": "https://api.github.com/users/espenfl/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 4031214816, "node_id": "MDU6TGFiZWw0MDMxMjE0ODE2", "url": "https://api.github.com/repos/inveniosoftware/invenio/labels/bug", "name": "bug", "color": "d73a4a", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2021-01-08T12:46:08Z", "updated_at": "2021-01-11T09:32:27Z", "closed_at": "2021-01-11T09:32:27Z", "author_association": "NONE", "active_lock_reason": null, "body": "Package version (if known): 3.4\r\n\r\n## Describe the bug\r\nUpon starting from a fresh Centos 8.2, installing python 3.8 using alt install, enabling a virtualenv for python 3.8 and following https://inveniosoftware.org/products/framework/ we get after `./scripts/bootstrap`:\r\n\r\n```\r\n(invenio) [espenfl@invenio my-site]$ more /home/espenfl/.npm/_logs/2021-01-08T12_26_47_788Z-debug.log\r\n0 info it worked if it ends with ok\r\n1 verbose cli [ '/usr/bin/node', '/usr/local/bin/npm', 'run-script', 'build' ]\r\n2 info using npm@6.14.9\r\n3 info using node@v10.21.0\r\n4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]\r\n5 info lifecycle invenio-assets@1.0.0~prebuild: invenio-assets@1.0.0\r\n6 info lifecycle invenio-assets@1.0.0~build: invenio-assets@1.0.0\r\n7 verbose lifecycle invenio-assets@1.0.0~build: unsafe-perm in lifecycle true\r\n8 verbose lifecycle invenio-assets@1.0.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/espenfl/\r\nenv/invenio/var/instance/assets/node_modules/.bin:/home/espenfl/env/invenio/bin:/home/espenfl/env/invenio/bin:/home/espenfl/.local/bin:/home\r\n/espenfl/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin\r\n9 verbose lifecycle invenio-assets@1.0.0~build: CWD: /home/espenfl/env/invenio/var/instance/assets\r\n10 silly lifecycle invenio-assets@1.0.0~build: Args: [ '-c',\r\n10 silly lifecycle   'NODE_PRESERVE_SYMLINKS=1 NODE_ENV=production webpack --config ./build/webpack.config.js' ]\r\n11 silly lifecycle invenio-assets@1.0.0~build: Returned: code: 1  signal: null\r\n12 info lifecycle invenio-assets@1.0.0~build: Failed to exec build script\r\n13 verbose stack Error: invenio-assets@1.0.0 build: `NODE_PRESERVE_SYMLINKS=1 NODE_ENV=production webpack --config ./build/webpack.config.js\r\n`\r\n13 verbose stack Exit status 1\r\n13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)\r\n13 verbose stack     at EventEmitter.emit (events.js:198:13)\r\n13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)\r\n13 verbose stack     at ChildProcess.emit (events.js:198:13)\r\n13 verbose stack     at maybeClose (internal/child_process.js:982:16)\r\n13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)\r\n14 verbose pkgid invenio-assets@1.0.0\r\n15 verbose cwd /home/espenfl/env/invenio/var/instance/assets\r\n16 verbose Linux 4.18.0-193.19.1.el8_2.x86_64\r\n17 verbose argv \"/usr/bin/node\" \"/usr/local/bin/npm\" \"run-script\" \"build\"\r\n18 verbose node v10.21.0\r\n19 verbose npm  v6.14.9\r\n20 error code ELIFECYCLE\r\n21 error errno 1\r\n22 error invenio-assets@1.0.0 build: `NODE_PRESERVE_SYMLINKS=1 NODE_ENV=production webpack --config ./build/webpack.config.js`\r\n22 error Exit status 1\r\n23 error Failed at the invenio-assets@1.0.0 build script.\r\n23 error This is probably not a problem with npm. There is likely additional logging output above.\r\n24 verbose exit [ 1, true ]\r\n```\r\n## Steps to Reproduce\r\nUpon starting from a fresh Centos 8.2, installing python 3.8 using alt install, enabling a virtualenv for python 3.8 and following https://inveniosoftware.org/products/framework/.\r\n", "reactions": {"url": "https://api.github.com/repos/inveniosoftware/invenio/issues/4082/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/inveniosoftware/invenio/issues/4082/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/inveniosoftware/invenio/issues/4049", "repository_url": "https://api.github.com/repos/inveniosoftware/invenio", "labels_url": "https://api.github.com/repos/inveniosoftware/invenio/issues/4049/labels{/name}", "comments_url": "https://api.github.com/repos/inveniosoftware/invenio/issues/4049/comments", "events_url": "https://api.github.com/repos/inveniosoftware/invenio/issues/4049/events", "html_url": "https://github.com/inveniosoftware/invenio/issues/4049", "id": 685939981, "node_id": "MDU6SXNzdWU2ODU5Mzk5ODE=", "number": 4049, "title": "\"dyld: Library not loaded\" when installing on OS X", "user": {"login": "pgorla", "id": 66346957, "node_id": "MDQ6VXNlcjY2MzQ2OTU3", "avatar_url": "https://avatars.githubusercontent.com/u/66346957?v=4", "gravatar_id": "", "url": "https://api.github.com/users/pgorla", "html_url": "https://github.com/pgorla", "followers_url": "https://api.github.com/users/pgorla/followers", "following_url": "https://api.github.com/users/pgorla/following{/other_user}", "gists_url": "https://api.github.com/users/pgorla/gists{/gist_id}", "starred_url": "https://api.github.com/users/pgorla/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/pgorla/subscriptions", "organizations_url": "https://api.github.com/users/pgorla/orgs", "repos_url": "https://api.github.com/users/pgorla/repos", "events_url": "https://api.github.com/users/pgorla/events{/privacy}", "received_events_url": "https://api.github.com/users/pgorla/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 4031214816, "node_id": "MDU6TGFiZWw0MDMxMjE0ODE2", "url": "https://api.github.com/repos/inveniosoftware/invenio/labels/bug", "name": "bug", "color": "d73a4a", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2020-08-26T01:40:22Z", "updated_at": "2020-08-26T02:01:27Z", "closed_at": "2020-08-26T02:01:27Z", "author_association": "NONE", "active_lock_reason": null, "body": "Package version (if known): The latest from the download page.\r\n\r\nPython 3.7.8\r\nFlask 1.1.2\r\nWerkzeug 0.16.1\r\nOS X Catalina, 0.15.6 (19G73)\r\n\r\n## Describe the bug\r\nHello, I've run into an installation error when trying to install invenio locally for testing. I am seeing this error.\r\n\r\n```\r\ndyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.66.dylib\r\nReferenced from: /usr/local/bin/node\r\nReason: image not found\r\n```\r\n\r\n## Steps to Reproduce\r\n1. Run `./scripts/bootstrap`, specifically it's this step that is failing: `pipenv run invenio webpack buildall`\r\n4. See error\r\n\r\n## Additional context\r\nI've been looking online and this looks like a known issue with OS X, but so far I have not found a workaround.", "reactions": {"url": "https://api.github.com/repos/inveniosoftware/invenio/issues/4049/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/inveniosoftware/invenio/issues/4049/timeline", "performed_via_github_app": null, "state_reason": "completed"}]